import type { CaseRecord } from "./types";

const R = "2026-08-05";

/**
 * One canonical record per institution, merged from all three source files.
 * Canonical hub file wins on facts/labels/attribution; deep-research wins on
 * structure; FSI_.txt contributes cases and narrative the others lack.
 * Missing fields render as "Not disclosed" — never inferred.
 */
export const CASES: CaseRecord[] = [
  {
    id: "wells-fargo",
    name: "Wells Fargo — “Fargo” virtual assistant",
    geo: "United States",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Scale everyday digital-banking servicing without exposing customer PII to LLMs.",
    capability: "Consumer-facing conversational assistant (voice + text) for card controls, transaction search and account servicing.",
    models: "Evolved from Dialogflow + PaLM 2 to Google Gemini Flash 2.0, orchestrated model-agnostically.",
    architecture:
      "Internal “Tachyon” platform built on three premises — no single model dominates, no single cloud, data portability is hard. Speech is transcribed locally → scrubbed/tokenized → a small language model detects PII → only sanitized intent/entities reach Gemini Flash. CIO Chintan Mehta: “We're poly-model and poly-cloud.”",
    governance: "Privacy-by-architecture: tokenize before the model call. Zero PII sent to the LLM.",
    outcomes: [
      { text: "“From 21.3 million interactions in 2023 to more than 245 million in 2024, with over 336 million cumulative interactions since launch” — more than double original projections, with zero human handoffs and zero PII exposed to the LLM.", label: "verified", sourceIds: ["venturebeat-apr25"] },
      { text: "~2.7 interactions per session; Spanish is 80%+ of usage.", label: "verified", sourceIds: ["venturebeat-apr25"] },
    ],
    lessons: "Privacy-by-architecture (tokenize before the model call) is what makes a consumer deployment defensible to regulators.",
    whyCompetitorsStruggle: "The privacy-preserving orchestration + model-agnostic platform is a build, not a buy — hard to replicate without deep cloud+ML engineering.",
    googlePosition: { text: "The flagship reference for consumer-scale, PII-safe conversational banking on Gemini. Use in every retail-bank CX conversation.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "venturebeat-apr25"],
    lastReviewed: R,
  },
  {
    id: "cba",
    name: "Commonwealth Bank of Australia (CBA)",
    geo: "Australia",
    segment: "retail",
    vendorIds: ["aws", "anthropic", "openai", "snowflake"],
    workflowIds: ["fraud", "customer-service"],
    stage: "bounded-agent",
    grade: "verified-production",
    guardrail: true,
    problem: "Scam/fraud losses; slow home-loan and small-business processes.",
    capability: "GenAI across fraud, scam prevention, customer messaging and lending processes; a 2026 agentic fraud system that proposes new detection rules.",
    models: "AWS/Anthropic and OpenAI (Australia banking partner; cites Claude for fraud/customer service).",
    dataPlatform: "The 2026 agentic fraud system runs on Snowflake, built in-house in three months, monitoring 80M+ signals/day.",
    outcomes: [
      { text: "GenAI tools “cut customer losses from scams in half”; frauds down 30%; an AI messaging app “trimmed call center customer wait times by 40% this year”; mortgage pre-approvals shortened “to as little as 10 minutes”; small-business annual reviews from 14 hours to 2. CEO Matt Comyn cited 50+ delivered use cases.", label: "verified", sourceIds: ["bloomberg-nov24"] },
    ],
    lessons: "A 2026 episode — a fraud ring used AI-generated documents to obtain up to ~A$1B in fraudulent home loans through CBA's broker channel (Strike Force Myddleton; 27+ charged as of May 2026) — is the cautionary flip-side: AI is both shield and weapon in fraud.",
    googlePosition: { text: "Use as competitive intel; counter with HSBC DRA (AML) and Wells Fargo (CX) as Google's equal-or-stronger proof points.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "bloomberg-nov24"],
    lastReviewed: R,
  },
  {
    id: "citi",
    name: "Citi — Stylus Workspaces + Citi Assist",
    geo: "Global (~175,000 employees, 80+ jurisdictions)",
    segment: "commercial",
    vendorIds: ["googlecloud", "anthropic"],
    workflowIds: ["software-eng", "customer-service"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Document-heavy knowledge work, multi-step workflows, developer productivity.",
    capability: "Proprietary Stylus Workspaces platform; agentic capabilities added Sept 2025 (pilot of 5,000). Companion tools: Citi Assist (policy/knowledge), Citi Stylus (document intelligence), coding assistant.",
    models: "Google Gemini and Anthropic Claude.",
    outcomes: [
      { text: "30,000 developers equipped with gen-AI coding tools (announced Q4 2024 earnings); 220,000 automated code reviews in Q1 2025; Citi spent $11.8B on technology in 2024. Head of AI: Shobhit Varshney (ex-IBM).", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Live proof that Gemini powers a top-5 global bank's core productivity platform alongside Claude — reinforces the model-agnostic “and, not or” narrative.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "deutsche-bank",
    name: "Deutsche Bank — DB Lumina",
    geo: "Germany / global",
    segment: "ib-research",
    vendorIds: ["googlecloud"],
    workflowIds: ["investment-research"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Research-analyst productivity (earnings notes, summarization, Q&A) under strict privacy.",
    capability: "AI research agent: ingestion, summarization, Q&A, editing; RAG-grounded.",
    models: "Gemini + Vertex AI.",
    architecture:
      "GKE microservices; Cloud SQL with pgvector; Cloud Storage for unstructured data; Gemini Embeddings API; guardrails; Google Cloud Observability; prompts stored in Cloud Storage, queried via BigQuery; auth via IDaaS integrated with Azure AD, authorization via dbEntitlements.",
    outcomes: [
      { text: "Live since Sept 2024; ~5,000 users across Research (Origination & Advisory, FICC), roadmap to 10,000+. Analysts report saving 30–45 minutes on earnings-note templates and up to two hours on other tasks.", label: "verified", sourceIds: ["canonical"] },
    ],
    whyCompetitorsStruggle: "Deep co-engineering with Google Cloud Consulting; RAG architecture tuned to DB's compliance posture.",
    googlePosition: { text: "THE flagship for investment-research agents on Gemini/Vertex. Lead capital-markets research conversations with this.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "morgan-stanley",
    name: "Morgan Stanley — AI @ Morgan Stanley Assistant / Debrief / AskResearchGPT",
    geo: "United States / global",
    segment: "ib-research",
    vendorIds: ["openai", "azure"],
    workflowIds: ["advisor-copilot", "investment-research"],
    stage: "assistive",
    grade: "verified-production",
    guardrail: true,
    problem: "Advisors could not efficiently access approved research and intellectual capital.",
    capability: "Bespoke OpenAI-powered assistant grounded in Morgan Stanley content; Debrief auto-generates client notes into CRM; development was eval-driven with OpenAI, using expert-developed evaluations and human review.",
    models: "OpenAI GPT-4 + Whisper; RAG over a large proprietary research corpus. Runs on Microsoft Azure.",
    governance: "Advisor remains accountable for the client interaction.",
    outcomes: [
      { text: "“To date, 98% of Financial Advisor teams have adopted the Assistant.”", label: "verified", sourceIds: ["ms-release"] },
      { text: "OpenAI's case study adds that advisor document access rose “from 20% to 80%.”", label: "verified", sourceIds: ["openai-case"] },
    ],
    conflict: "Corpus size is reported inconsistently across sources: Morgan Stanley cites 100,000+ documents; some sources cite 350,000+. The canonical file surfaces both; neither is silently preferred.",
    googlePosition: { text: "The strongest OpenAI FSI reference. Counter with Deutsche Bank Lumina and emphasize Gemini's 1M-token context, data residency, and avoidance of single-model lock-in.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "ms-release", "openai-case", "research-file"],
    lastReviewed: R,
  },
  {
    id: "jpmorgan",
    name: "JPMorgan Chase — LLM Suite + Connect Coach",
    geo: "Global (230,000+ employees)",
    segment: "wealth-asset",
    vendorIds: ["openai", "anthropic", "inhouse"],
    workflowIds: ["customer-service", "fraud", "advisor-copilot"],
    stage: "multi-agent",
    grade: "verified-production",
    problem: "Firm-wide knowledge-worker productivity.",
    capability: "In-house, model-agnostic gen-AI hub; custom assistants; document analysis; data viz; an agentic roadmap.",
    models: "Multi-provider (OpenAI + Anthropic + others; ~7 specialized LLMs) inside a controlled, audited environment; updated roughly every 8 weeks; centralized knowledge graph shared with Connect Coach and SpectrumGPT.",
    governance: "JPMorgan bans external consumer chatbots “like ChatGPT or Google Gemini” for work over data-privacy concerns, building LLM Suite in-house atop an $18B+ annual technology budget.",
    outcomes: [
      { text: "~200,000 employees onboarded within 8 months (≈two-thirds of the workforce); 450+ production use cases; roadmap to 1,000 by end-2026; users save 3–6 hours/week.", label: "verified", sourceIds: ["canonical"] },
      { text: "President/COO Daniel Pinto (Barclays conference, Sept 2024) estimated up to $1.5B in AI value — later characterized as “closer to $2 billion” — noting “A lot of that is related to prevention of fraud.”", label: "company", sourceIds: ["canonical"] },
    ],
    whyCompetitorsStruggle: "An $18B-class tech budget; a full in-house build is feasible only for the largest banks.",
    googlePosition: { text: "LLM Suite is a reference architecture, not a buyable product. Google's pitch to Tier-2/3 banks: get JPMorgan-class capability via Gemini Enterprise + Vertex without an $18B budget.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "research-file"],
    lastReviewed: R,
  },
  {
    id: "goldman-sachs",
    name: "Goldman Sachs — GS AI Assistant / Developer Copilot / Devin",
    geo: "United States / global",
    segment: "ib-research",
    vendorIds: ["openai", "googlecloud", "anthropic"],
    workflowIds: ["software-eng", "investment-research"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Firm-wide knowledge-worker and engineering productivity.",
    capability: "GS AI Assistant firmwide; Developer Copilot; adopting Cognition's Devin as an agentic “virtual colleague”; Banker Copilot, Legend AI Query, Translate AI.",
    models: "Multi-model: GPT-4o/o3-mini, Gemini 2.0 Flash/Pro, Claude 3.7 Sonnet, open models.",
    outcomes: [
      { text: "GS AI Assistant went firmwide (46,500 knowledge workers) on June 23, 2025; the Developer Copilot reaches 12,000+ engineers (up to ~20% efficiency); staff now write ~a million gen-AI prompts a month.", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Evidence for the copilot → agent → multi-agent progression and for the poly-model buying pattern; Gemini is already inside Goldman's mix.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "bridgewater",
    name: "Bridgewater (AIA Labs) — Investment Analyst Assistant",
    geo: "United States",
    segment: "wealth-asset",
    vendorIds: ["anthropic"],
    workflowIds: ["investment-research"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Investment analysis productivity.",
    capability: "Investment Analyst Assistant (Python code generation, visualizations) since 2023.",
    models: "Anthropic Claude.",
    outcomes: [
      { text: "In production since 2023 as part of Claude for Financial Services (launched July 15, 2025; 10 pre-built finance agents May 2026; LSEG/Moody's connectors; Claude for Excel).", label: "verified", sourceIds: ["canonical"] },
    ],
    lessons: "Anthropic's own deployment guide tells finance clients to avoid piloting Claude on high-stakes work and to keep analysts reviewing every output; when Claude has actually traded, it reportedly lost money — a sober counter to “autonomous trading” hype.",
    googlePosition: { text: "Claude is a first-class model in Vertex AI Model Garden — sell “Claude on Google Cloud” (data stays in the customer's Google tenancy) vs. Claude on AWS Bedrock.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "fortune-may26"],
    lastReviewed: R,
  },
  {
    id: "nbim",
    name: "NBIM (Norges Bank Investment Management)",
    geo: "Norway",
    segment: "wealth-asset",
    vendorIds: ["anthropic"],
    workflowIds: ["investment-research"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Analyst productivity at the sovereign wealth fund.",
    capability: "Claude-based assistance for investment work.",
    models: "Anthropic Claude.",
    outcomes: [
      { text: "~20% weekly time saved; 600+ active users within two months.", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Anthropic reference; the counter is Claude as a first-class model on Vertex under Google Cloud controls.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "aig",
    name: "AIG — underwriting review with Claude",
    geo: "United States",
    segment: "insurance",
    vendorIds: ["anthropic"],
    workflowIds: ["insurance-ops", "credit-underwriting"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Slow underwriting review.",
    capability: "Claude-assisted underwriting review.",
    models: "Anthropic Claude.",
    outcomes: [
      { text: "Underwriting review time compressed >5x; data accuracy improved from 75% to over 90% (CEO Peter Zaffino).", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "The highest-value insurance workflows are AI-assisted underwriting and claims adjudication; Google should lead with Document AI + Gemini for claims and BigQuery for actuarial data. Insurtechs run multi-cloud; no single dominant insurance-AI cloud yet — an opening for Google.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "fortune-may26"],
    lastReviewed: R,
  },
  {
    id: "klarna",
    name: "Klarna — OpenAI customer-service assistant",
    geo: "Global (23 markets, 35+ languages)",
    segment: "payments-fintech",
    vendorIds: ["openai"],
    workflowIds: ["customer-service"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "High-volume customer support across languages and markets.",
    capability: "OpenAI-powered assistant for refunds, returns, payments and service workflows. The definitive pre/post-mortem.",
    models: "OpenAI.",
    outcomes: [
      { text: "“2.3 million conversations… doing the equivalent work of 700 full-time agents… estimated to drive a $40 million USD in profit improvement to Klarna in 2024”; two-thirds of chats automated; resolution 11 min → <2 min; 25% fewer repeat inquiries.", label: "company", sourceIds: ["klarna-openai-feb24"] },
      { text: "The 2025 walk-back — CEO Sebastian Siemiatkowski: “cost… seems to have been a too predominant evaluation factor when organizing this, [and] what you end up having is lower quality.” Klarna reintroduced human agents and 24/7 live chat.", label: "verified", sourceIds: ["canonical"] },
    ],
    lessons: "This is the single most important “lessons learned” case in the hub: measure first-contact resolution, repeat contact, complaints and customer trust — not only labour-equivalent capacity.",
    googlePosition: { text: "Use to sell human-in-the-loop design, eval-driven quality gates (Vertex AI Evaluation), and CCAI with graceful human handoff — not maximal deflection.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "klarna-openai-feb24", "research-file"],
    lastReviewed: R,
  },
  {
    id: "nubank",
    name: "Nubank — agentic customer support at 100M+ scale",
    geo: "Brazil / LatAm (100M+ users)",
    segment: "payments-fintech",
    vendorIds: ["openai", "inhouse"],
    workflowIds: ["customer-service"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Support at 100M+ customer scale.",
    capability: "Five production agents (card delivery, debt management, credit-limit support, card management, product explanation); evaluation-driven framework (context engineering, human-in-the-loop prompt iteration, LLM-judge with GEPA optimization).",
    models: "OpenAI GPT-4o + in-house models (via the Hyperplane acquisition).",
    governance: "DPAs contractually prohibit training on Nubank data; agents make no unconstrained/irrevocable credit decisions.",
    outcomes: [
      { text: "8.5M monthly contacts, 55–60% first handled by LLMs; a 37-percentage-point NPS gain and 29-point self-service gain in large-scale A/B tests; 20x faster agent shipping via simulation.", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Blueprint for eval-driven agent ops; map to Vertex AI Agent Engine + Evaluation.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "payments-standards",
    name: "Agentic payments standards — AP2 / x402 / Visa / Stripe",
    geo: "Global",
    segment: "payments-fintech",
    vendorIds: ["googlecloud", "openai"],
    workflowIds: ["agentic-commerce"],
    stage: "multi-agent",
    grade: "announced",
    problem: "Agent-initiated payments need a trusted, interoperable mandate standard.",
    capability: "Google AP2 (Agent Payments Protocol): announced Sept 16, 2025 with 60+ launch partners (Mastercard, PayPal, American Express, Coinbase, Salesforce, JCB, Worldpay). Open and payment-agnostic; cryptographically-signed Mandates (Intent, Cart, Payment) carried as W3C Verifiable Credentials; extends A2A and MCP; an x402 extension (with Coinbase, Ethereum Foundation, MetaMask) supports stablecoins. Apache 2.0; latest release v0.2.0 (April 2026).",
    architecture:
      "PayPal + Google Cloud co-announced a Conversational Commerce Agent on Oct 27, 2025. Visa Intelligent Commerce / Trusted Agent Protocol launched Apr 30, 2025 (partners include OpenAI, Microsoft, Anthropic, Stripe); Intelligent Commerce Connect unifies four agent protocols. Stripe: Agentic Commerce Suite (Dec 2025); co-authored the Agentic Commerce Protocol (ACP) with OpenAI. Both card networks joined AP2. Mastercard Agent Pay detail lives on the Mastercard record.",
    outcomes: [
      { text: "Google owns the neutral, open standard (AP2) that the card networks joined — a defining Google differentiator vs. OpenAI's proprietary ACP. As Google frames it, the battleground shifts “from mobile wallets to the AI agent's preferred payment method.”", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "For banks/payments clients, AP2 ownership is the lead story; A2A/MCP interop is the connective tissue.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "mastercard",
    name: "Mastercard — Decision Intelligence Pro + Agent Pay",
    geo: "Global",
    segment: "payments-fintech",
    vendorIds: ["inhouse"],
    workflowIds: ["fraud", "agentic-commerce"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Real-time transaction fraud detection and false declines.",
    capability: "Decision Intelligence Pro applies graph techniques and generative-AI-derived models to relationships among accounts, merchants, devices and transactions using Mastercard network intelligence. Separately, Agent Pay (launched Apr 29, 2025): Agentic Tokens bind a credential to an agent identity; Citi + US Bank pilot Sept 2025; all US Mastercard cardholders Nov 2025; “Agent Pay for Machines” (2026). Mastercard joined AP2.",
    outcomes: [
      { text: "Initial modelling indicated an average 20% improvement in fraud detection, with higher gains in selected cases, decisions in milliseconds and materially fewer false positives.", label: "company", sourceIds: ["research-file"] },
    ],
    whyCompetitorsStruggle: "The moat is the payment-network graph and real-time decision infrastructure.",
    googlePosition: { text: "Google's role is more likely infrastructure, analytics, model operations and adjacent issuer workflows than displacement of the network model.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["canonical", "research-file"],
    lastReviewed: R,
  },
  {
    id: "nasdaq",
    name: "Nasdaq — market surveillance & data platform",
    geo: "United States / global",
    segment: "market-infra",
    vendorIds: ["aws"],
    workflowIds: ["fraud", "investment-research"],
    stage: "assistive",
    grade: "verified-production",
    guardrail: true,
    problem: "Massive overnight data ingestion of up to 60 billion records caused processing bottlenecks, threatening strict reporting and billing SLAs before market open; investigation and review of suspected market abuse.",
    capability: "Scalable market surveillance, automated distillation of regulatory filings and anomaly detection (“Eqlipse Intelligence”; AWS partnership expanded May 2025); generative AI embedded in the surveillance platform to help investigators navigate alerts and unstructured evidence, with broader client availability planned from late 2025.",
    models: "Amazon Bedrock / SageMaker.",
    dataPlatform: "Transitioned from legacy on-premises data warehouses to a data lake on AWS: data written to Amazon S3, queried in parallel via Amazon Redshift Spectrum.",
    governance: "Highly regulated market-abuse detection frameworks requiring extreme accuracy and auditability.",
    outcomes: [
      { text: "90% improvement in critical billing processes (40 minutes → 4 minutes) and a 60–70% performance improvement across all overnight batch processes.", label: "company", sourceIds: ["fsi-txt"] },
      { text: "Nasdaq states AI streamlines triage and examination and improves the efficiency and quality of suspected-abuse investigations; customer-level ROI is not disclosed.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "NOT a Google Cloud win — market infrastructure is Google's clearest FSI competitive gap. Target custodians and post-trade (reconciliation, corporate actions, reporting) with a data-platform + sovereign + security narrative rather than trying to win exchange matching engines. The BigQuery counter-position: unified serverless architecture and Continuous Queries versus a federated S3/Redshift design.", label: "analysis", sourceIds: ["canonical", "fsi-txt"] },
    sourceIds: ["canonical", "fsi-txt", "research-file"],
    lastReviewed: R,
  },
  {
    id: "lseg",
    name: "LSEG — financial data via Microsoft Copilot",
    geo: "United Kingdom / global",
    segment: "market-infra",
    vendorIds: ["azure"],
    workflowIds: ["investment-research"],
    stage: "assistive",
    grade: "verified-production",
    guardrail: true,
    problem: "Expose market and financial data inside AI workflows.",
    capability: "Financial data exposed to Microsoft Copilot via an LSEG-managed MCP server; “33+ petabytes” of AI-ready content (Oct 13, 2025).",
    models: "Microsoft Copilot ecosystem.",
    outcomes: [
      { text: "Announced Oct 13, 2025. Not a Google Cloud win.", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Competitive intel only. Counter at the data-platform and interop layer (BigQuery + A2A/MCP), not by feature-matching Copilot distribution.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "hsbc",
    name: "HSBC — Dynamic Risk Assessment + risk data on Google Cloud",
    geo: "United Kingdom / global",
    segment: "commercial",
    vendorIds: ["googlecloud", "mistral"],
    workflowIds: ["fraud", "treasury-risk", "advisor-copilot"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Find financial crime at scale without drowning investigators in false positives; slow scenario analysis over large, diverse risk datasets.",
    capability: "Dynamic Risk Assessment AML on Google Cloud; Google Cloud Storage, Dataflow and BigQuery accelerate risk-scenario modelling; RM + AI insights in commercial banking; a 2026 gen/agentic-AI expansion; a multi-year Mistral deal (Dec 2025).",
    models: "AML AI on Google Cloud; model details for the risk platform are not publicly disclosed.",
    outcomes: [
      { text: "“Two to four times more financial crime… 60% fewer false positives.”", label: "verified", sourceIds: ["canonical"] },
      { text: "600+ AI use cases; 600+ apps on Google Cloud; faster time to risk and trading decisions (quantified ROI not disclosed).", label: "verified", sourceIds: ["canonical", "research-file"] },
    ],
    googlePosition: { text: "Google's lead AML/financial-crime proof and the data-first risk story: AI differentiation depends on governed, timely, scalable risk data before an agent or foundation model is introduced.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical", "research-file"],
    lastReviewed: R,
  },
  {
    id: "bbva",
    name: "BBVA — ChatGPT Enterprise firmwide",
    geo: "Spain / global",
    segment: "retail",
    vendorIds: ["openai"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Employee productivity at bank scale.",
    capability: "ChatGPT Enterprise rollout to all 120,000 employees (announced Dec 12, 2025).",
    models: "OpenAI.",
    outcomes: [
      { text: "~3 hours/week saved per user (company-stated, cited in the workflow evidence table).", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "OpenAI's employee-productivity reference; the Google counter is Gemini Enterprise with permission-aware search over the systems employees already use.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "seb",
    name: "SEB — wealth agent",
    geo: "Sweden",
    segment: "wealth-asset",
    vendorIds: ["googlecloud"],
    workflowIds: ["advisor-copilot"],
    stage: "bounded-agent",
    grade: "production-undisclosed",
    problem: "Advisor efficiency.",
    capability: "Wealth agent on Google Cloud.",
    outcomes: [
      { text: "+15% efficiency.", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "European wealth proof point on the Google stack.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "starling",
    name: "Starling Bank — Gemini Enterprise",
    geo: "United Kingdom",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "production-undisclosed",
    problem: "Employee AI access at a digital bank.",
    capability: "Gemini Enterprise deployment.",
    outcomes: [
      { text: "Named Google Cloud FSI reference; quantified outcomes not disclosed.", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Digital-bank reference for Gemini Enterprise.", label: "verified", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "lloyds",
    name: "Lloyds Banking Group — common ML/AI platform",
    geo: "United Kingdom",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["software-eng"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Inability to conduct ML experimentation at scale on the previous platform.",
    capability: "Migration to Vertex AI (now within Gemini Enterprise Agent Platform) as the common managed ML platform — an enterprise AI factory rather than a single use case.",
    outcomes: [
      { text: "More than 300 data scientists and AI developers on the platform; zero unplanned platform downtime; 80 ML experiments created in six months.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "The common-AI-platform story: standardised tooling, reliability and reusable controls.", label: "verified", sourceIds: ["canonical", "research-file"] },
    sourceIds: ["canonical", "research-file"],
    lastReviewed: R,
  },
  {
    id: "scotiabank",
    name: "Scotiabank — Google Cloud platform + the data-quality lesson",
    geo: "Canada",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Contact-center agents needed a knowledge base; the initial gen-AI deployment gave highly inaccurate answers.",
    capability: "Generative AI overlay on a corporate knowledge base; Vertex AI / Gemini / CCAI; Google Cloud named Scotiabank's “enterprise cloud platform of choice,” serving ~55M customers.",
    dataPlatform: "Initially a standard RAG deployment, overhauled organically by the internal business team focusing strictly on data quality and curation; ownership of the data pipeline shifted from centralized IT to the contact-center team.",
    outcomes: [
      { text: "Answer accuracy improved from 33% to approximately 96%; internal remediation took months, avoiding an estimated $10 million, 12-month external consulting engagement.", label: "company", sourceIds: ["fsi-txt"] },
    ],
    lessons: "An advanced model cannot overcome poor enterprise data. The deployment succeeded only when the business unit took ownership of the unstructured data before embedding it.",
    googlePosition: { text: "Validates that the data platform is more critical than the model: position Dataplex + BigQuery to enforce data-quality rules and lineage, preventing the “garbage in, garbage out” cycle.", label: "analysis", sourceIds: ["fsi-txt"] },
    sourceIds: ["canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "temenos",
    name: "Temenos — Copilot for Core + FCM AI Agent",
    geo: "Switzerland / global (ISV)",
    segment: "commercial",
    vendorIds: ["azure"],
    workflowIds: ["kyc-onboarding", "fraud"],
    stage: "bounded-agent",
    grade: "verified-production",
    problem: "Sanctions screening and core-banking AI for bank customers.",
    capability: "FCM AI Agent — a Tier-1 bank now processes hundreds of thousands of sanctions-screening cases and automates 20%+ of alerts; runs on Azure OpenAI.",
    models: "Azure OpenAI.",
    outcomes: [
      { text: "Tier-1 bank: hundreds of thousands of sanctions-screening cases processed; 20%+ of alerts automated.", label: "company", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "Most FSI ISVs embed Azure OpenAI today — a competitive gap Google should close via Vertex partnerships; negotiate model choice into ISV contracts.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "finastra",
    name: "Finastra — Assist.AI (trade finance)",
    geo: "United Kingdom / global (ISV)",
    segment: "commercial",
    vendorIds: ["azure"],
    workflowIds: ["kyc-onboarding"],
    stage: "assistive",
    grade: "production-undisclosed",
    problem: "Trade-finance document workflows for 7,000+ institutions.",
    capability: "Assist.AI embedded in Trade Innovation using Microsoft Azure OpenAI Service with vector DB + context-aware RAG.",
    models: "Microsoft Azure OpenAI Service.",
    outcomes: [
      { text: "Embedded ISV capability; quantified outcomes not disclosed.", label: "verified", sourceIds: ["canonical"] },
    ],
    googlePosition: { text: "An ISV app on Azure; Google should counter at the platform layer (data gravity + agent interoperability) rather than feature-match the ISV app.", label: "analysis", sourceIds: ["canonical"] },
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
  {
    id: "discover",
    name: "Discover Financial Services — contact-center knowledge",
    geo: "United States",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "verified-production",
    problem: "As digital self-service grew, contact-center agents fielded only the most complex queries and needed minutes to locate procedural documents across fragmented systems.",
    capability: "Document processing and customer-support assistance with generative AI.",
    models: "Google Cloud Vertex AI and Gemini.",
    architecture: "RAG grounding responses strictly in Discover's verified procedure documentation.",
    governance: "Strict human-in-the-loop oversight: technical writers draft with AI; human legal and compliance officers review before anything enters the production knowledge base.",
    outcomes: [
      { text: "70% reduction in agent search time — resolution times from minutes to seconds, keeping agents in the conversational flow.", label: "company", sourceIds: ["fsi-txt"] },
    ],
    whySucceeded: "Addressed a specific, measurable bottleneck while maintaining regulatory compliance; legal, compliance and infosec involved from inception.",
    googlePosition: { text: "Native Vertex AI + Enterprise Search grounding reduces the engineering overhead of custom RAG pipelines versus bespoke builds on AWS or Azure.", label: "analysis", sourceIds: ["fsi-txt"] },
    sourceIds: ["fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "zurich",
    name: "Zurich Insurance Group — underwriting & claims documents",
    geo: "Switzerland / global",
    segment: "insurance",
    vendorIds: ["azure"],
    workflowIds: ["insurance-ops"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Complex, non-standard claims and underwriting across geographies, languages and unstructured formats caused severe manual processing delays.",
    capability: "AI-powered underwriting automation and automated claims document processing.",
    models: "Microsoft Azure OpenAI and Azure AI.",
    architecture: "Deep API integration with Zurich's global enterprise systems; models ingest, classify and analyze unstructured documents in multiple languages, flowing insights into the underwriter's existing dashboard.",
    governance: "Real-time dashboards monitor process accuracy, automation rates and validation results.",
    outcomes: [
      { text: "Document processing speeds increased 50x; rapid quote responses; underwriter capacity freed for nuanced risk analysis.", label: "company", sourceIds: ["fsi-txt"] },
    ],
    googlePosition: { text: "Pivot the conversation to the limits of chained API calls: Gemini's large multimodal context ingests hundreds of pages in a single pass, and Confidential Space cryptographically isolates sensitive loss data during processing.", label: "analysis", sourceIds: ["fsi-txt"] },
    conflict: "FSI_.txt attributes a “2-million token context window” to Gemini 1.5 Pro in its positioning language; the canonical file states a 1M-token context for current Gemini models. The canonical figure is used everywhere on this site.",
    sourceIds: ["fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "prudential",
    name: "Prudential Financial — multi-agent advisor platform",
    geo: "United States",
    segment: "wealth-asset",
    vendorIds: ["aws"],
    workflowIds: ["advisor-copilot"],
    stage: "multi-agent",
    grade: "verified-production",
    problem: "Over 100,000 financial advisors faced fragmented workflows across dozens of disconnected IT systems for client engagement, quoting, product information and servicing.",
    capability: "Multi-agent orchestration and microservices-based AI platform built with the AWS GenAI Innovation Center: an orchestration agent routes natural-language requests to specialized sub-agents (quick quote, forms, book of business) while maintaining context.",
    governance: "Standardized frameworks for authentication, LLM gateway access and observability across all sub-agent interactions.",
    outcomes: [
      { text: "Time-to-value for new agent deployments reduced from 6–8 weeks to 3–4 weeks; cross-business reusability of agentic components.", label: "company", sourceIds: ["fsi-txt"] },
    ],
    whySucceeded: "A platform approach solved the scaling complexity of deploying gen AI to 100,000 advisors; independent teams build capabilities concurrently.",
    googlePosition: { text: "AWS simulated multi-agent via custom microservices; ADK + Agent Engine provide native multi-agent scaffolding and A2A standardizes agent discovery/delegation — aiming to beat the 3–4-week benchmark without custom routing plumbing.", label: "analysis", sourceIds: ["fsi-txt"] },
    sourceIds: ["fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "block",
    name: "Block (Square) — utility-based fraud agents",
    geo: "Global",
    segment: "payments-fintech",
    vendorIds: ["databricks"],
    workflowIds: ["fraud"],
    stage: "multi-agent",
    grade: "production-undisclosed",
    problem: "Continuous monitoring of massive transaction volumes to detect and adapt to evolving fraud patterns without adding latency to the payment flow.",
    capability: "Multi-agent ecosystem using utility-based agents and reinforcement learning for dynamic policy optimization — balancing fraud loss against false positives via a utility function, adapting policies as fraudsters change tactics.",
    dataPlatform: "Databricks ecosystem deployed over hyperscaler infrastructure.",
    governance: "Strong requirements for explainability, auditability and controlled autonomy.",
    outcomes: [
      { text: "Risk teams identify suspicious activity faster and adapt strategies autonomously while maintaining strict performance SLAs across high-volume environments (quantified figures not disclosed).", label: "company", sourceIds: ["fsi-txt"] },
    ],
    googlePosition: { text: "Counter Databricks' ML mindshare with Vertex MLOps, Feature Store and native evaluation; Agent Engine's secure runtime removes the premium consumption cost of orchestrating models that already run on cloud infrastructure.", label: "analysis", sourceIds: ["fsi-txt"] },
    sourceIds: ["fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "bofa",
    name: "Bank of America — Erica",
    geo: "United States",
    segment: "retail",
    vendorIds: ["inhouse"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "verified-production",
    problem: "High-volume customer self-service and personalised financial guidance.",
    capability: "Erica is embedded in the mobile experience, connecting customers to account information, card controls, transaction search and specialists.",
    models: "Underlying model and data architecture are not publicly disclosed.",
    outcomes: [
      { text: "In 2025, 20.6 million customers used Erica nearly 700 million times; cumulative interactions passed 3.2 billion by March 2026.", label: "company", sourceIds: ["research-file"] },
    ],
    lessons: "Durable value comes from deep workflow integration, proactive insights and years of interaction refinement — not from a standalone chatbot.",
    googlePosition: { text: "Mass-adoption benchmark for consumer AI; the Google counter is Wells Fargo's Fargo on Gemini.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "federal-bank",
    name: "Federal Bank — multilingual servicing (India)",
    geo: "India",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "production-undisclosed",
    problem: "Multilingual servicing, product discovery and fintech integration.",
    capability: "Dialogflow CX, Vertex AI and Gemini; Compute Engine; Firebase employee application; BigQuery; Google Cloud APIs; Cloud Armor.",
    governance: "The bank states its customer data is not used to train foundation models and retains a human-service option.",
    outcomes: [
      { text: "Live 24×7 multilingual assistance, more conversational search and automated API-support workflows; the bank describes the deployment as transformational but does not publish ROI.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "The strong India reference for joining conversational AI, APIs, analytics and security rather than pitching a model in isolation.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "hong-leong",
    name: "Hong Leong Bank — multi-workload adoption",
    geo: "Malaysia",
    segment: "retail",
    vendorIds: ["googlecloud"],
    workflowIds: ["customer-service", "software-eng", "kyc-onboarding"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Customer support, employee productivity and software development.",
    capability: "Gemini 2.5 Flash through Gemini Enterprise Agent Platform, including a private model instance; customer and employee chatbots; Document AI for trade operations; Gemini Code Assist.",
    outcomes: [
      { text: "67% of customer-support queries handled by the chatbot; 99% AI accuracy for the cited implementation; 25% faster development with Gemini Code Assist.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "A multi-workload adoption path: customer service, documents and engineering on a common governed platform.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "berenberg",
    name: "Berenberg — equity research on Gemini Enterprise",
    geo: "Germany",
    segment: "ib-research",
    vendorIds: ["googlecloud"],
    workflowIds: ["investment-research"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Time-intensive research-content production.",
    capability: "Gemini Enterprise deployed across the institution; generative workflows support equity-research content. Precise retrieval/control architecture not fully disclosed.",
    outcomes: [
      { text: "Selected equity-research content generated 85–90% faster, enabling wider coverage with the same teams.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "High-quality European proof for domain-grounded knowledge work with analysts kept accountable.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "bny",
    name: "BNY — Eliza (model-agnostic enterprise platform)",
    geo: "United States / global",
    segment: "market-infra",
    vendorIds: ["googlecloud", "openai", "anthropic", "inhouse"],
    workflowIds: ["customer-service", "treasury-risk"],
    stage: "multi-agent",
    grade: "verified-production",
    problem: "Fragmented operational data and manual lifecycle activity in asset servicing and private credit.",
    capability: "Eliza: a model-agnostic enterprise platform supporting models from Google, OpenAI and Anthropic with multi-agent functionality; parses vendor data into systems of record and automates parts of private-credit processing and reporting.",
    outcomes: [
      { text: "BNY confirms production deployment and broad workforce use; its annual-report site describes Eliza as multi-agentic and model-agnostic.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "The customer's likely target state: a governed internal AI control plane that prevents any single model provider from becoming the enterprise architecture. Google's play is to be the best home for it.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "blackrock",
    name: "BlackRock — Aladdin Copilot",
    geo: "Global",
    segment: "wealth-asset",
    vendorIds: ["inhouse"],
    workflowIds: ["advisor-copilot", "investment-research"],
    stage: "assistive",
    grade: "production-undisclosed",
    problem: "Navigating portfolio, risk and market information inside Aladdin.",
    capability: "Aladdin Copilot embedded in the platform; Auto Commentary combines Aladdin risk analytics, Morgan Stanley data and advisor workflows; users remain responsible for investment decisions.",
    outcomes: [
      { text: "Production availability confirmed; broad quantitative ROI not disclosed.", label: "company", sourceIds: ["research-file"] },
    ],
    lessons: "An incumbent application vendor can capture the AI interface because it owns workflow context, permissions and domain data.",
    googlePosition: { text: "Google must enable and complement such platforms, not assume it replaces them.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "john-hancock",
    name: "John Hancock — Quick Quote underwriting",
    geo: "United States",
    segment: "insurance",
    vendorIds: ["inhouse"],
    workflowIds: ["insurance-ops", "credit-underwriting"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Slow preliminary underwriting and quote preparation.",
    capability: "Quick Quote uses generative AI to analyse application information and prepare preliminary underwriting responses. Detailed model and hosting information is not publicly disclosed.",
    outcomes: [
      { text: "A process that could take a day was reduced to roughly 15 minutes, with more than 4,000 requests per month reported in early 2026.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "Analogue for commercial credit, mortgage and insurance-document workflows: AI assembles evidence and recommendations while an authorised professional owns the decision.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "manulife",
    name: "Manulife — contact-centre + document AI",
    geo: "North America / global",
    segment: "insurance",
    vendorIds: ["inhouse"],
    workflowIds: ["customer-service", "insurance-ops"],
    stage: "assistive",
    grade: "verified-production",
    problem: "Agents navigating high volumes of complex policy information.",
    capability: "Generative AI tools retrieve source-backed answers with confidence signals for contact-centre staff; separate document solutions summarise leases and other complex materials.",
    outcomes: [
      { text: "Contact-centre tools support an operation handling ~110 million calls annually; the lease workflow cut initial analysis from six-to-eight hours to around ten minutes and overall review time by about half.", label: "company", sourceIds: ["research-file"] },
    ],
    lessons: "Citations, confidence indicators and human review are what make regulated knowledge assistance viable.",
    googlePosition: { text: "Maps to Document AI + Gemini + grounded answers with citation display.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "commerzbank",
    name: "Commerzbank — Ava",
    geo: "Germany",
    segment: "retail",
    vendorIds: ["azure"],
    workflowIds: ["customer-service"],
    stage: "bounded-agent",
    grade: "verified-production",
    guardrail: true,
    problem: "Scaling customer conversations while retaining compliance controls.",
    capability: "Ava uses Azure AI Foundry Agent Service, Azure Content Safety and Cosmos DB for shared conversational context; sensitive information is filtered before model interaction.",
    models: "Microsoft Azure stack.",
    outcomes: [
      { text: "More than 30,000 monthly conversations and approximately 75% autonomous resolution reported in late 2025.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "Microsoft's governed customer-facing agent reference. Google should position Model Armor, Agent Platform controls, customer-data grounding and omnichannel integration.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "discovery-bank",
    name: "Discovery Bank — Azure orchestration architecture",
    geo: "South Africa",
    segment: "retail",
    vendorIds: ["azure", "databricks"],
    workflowIds: ["customer-service"],
    stage: "assistive",
    grade: "production-undisclosed",
    guardrail: true,
    problem: "Personalised recommendations and service-agent assistance.",
    capability: "Azure OpenAI models, Azure Databricks, API Management, Container Apps/App Service and Cosmos DB; API Management centralises security, throttling and monitoring; model-failure categories are explicitly tuned.",
    models: "Azure OpenAI.",
    outcomes: [
      { text: "Production client and agent-assist applications confirmed; quantified productivity or revenue outcomes not disclosed.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "Competitive architecture showing a secure API and orchestration layer matters as much as model quality.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "ubs",
    name: "UBS — advisor smart assistants",
    geo: "Switzerland / global",
    segment: "wealth-asset",
    vendorIds: ["azure"],
    workflowIds: ["advisor-copilot"],
    stage: "assistive",
    grade: "production-undisclosed",
    guardrail: true,
    problem: "Fragmented content and complex advisor workflows.",
    capability: "Azure OpenAI Service and Azure AI Search power smart assistants that retrieve information for client advisors.",
    models: "Azure OpenAI Service.",
    outcomes: [
      { text: "Production use confirmed; Microsoft and UBS cite greater efficiency and client engagement, but no quantified public ROI.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "Microsoft is strong where content search, Azure data and workplace distribution are established. Lead with open architecture, data unification and agent governance.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "bank-of-singapore",
    name: "Bank of Singapore — agentic onboarding (announced)",
    geo: "Singapore",
    segment: "wealth-asset",
    vendorIds: ["inhouse"],
    workflowIds: ["kyc-onboarding"],
    stage: "bounded-agent",
    grade: "announced",
    problem: "Client onboarding taking more than 30 business days.",
    capability: "Announced agentic onboarding initiative intended to halve the process.",
    outcomes: [
      { text: "Target: reduce onboarding from more than 30 business days to 15. Announced intention; no deployment evidence yet.", label: "company", sourceIds: ["research-file"] },
    ],
    googlePosition: { text: "Evidence that private banking treats onboarding as the agentic entry point; map to Document AI + Agent Platform + graph screening.", label: "analysis", sourceIds: ["research-file"] },
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
];
