import { CASES } from "./cases";
import type { Hub, Workflow } from "./types";

const R = "2026-08-05";

/**
 * Composite scoring model from the deep-research report:
 * value 30% · readiness 20% · executive priority 15% · ROI evidence 15% ·
 * ease 20% (ease = 6 − complexity, on the report's five-point scales).
 */
export const DEFAULT_WEIGHTS = { value: 30, readiness: 20, exec: 15, roi: 15, ease: 20 };

export function composite(
  s: NonNullable<Workflow["scores"]>,
  w: typeof DEFAULT_WEIGHTS,
): number {
  const total = w.value + w.readiness + w.exec + w.roi + w.ease;
  if (total === 0) return 0;
  const raw =
    s.value * w.value +
    s.readiness * w.readiness +
    s.exec * w.exec +
    s.roi * w.roi +
    (6 - s.complexity) * w.ease;
  return raw / total;
}

const WORKFLOWS: Workflow[] = [
  {
    id: "customer-service",
    name: "Customer service & employee agent assist",
    scores: { value: 5, readiness: 5, complexity: 2, exec: 5, roi: 5 },
    printedComposite: 4.8,
    rationale: "High volume, strong production evidence and easy baseline metrics. Bank of America, Klarna, Commerzbank, Federal Bank and Manulife demonstrate scale.",
    current: "Agent searches multiple systems, interprets policy, writes notes and completes after-call work.",
    future: "AI identifies intent, retrieves approved answers, summarises context, proposes actions and completes authorised low-risk tasks.",
    decisionRights: "A person handles vulnerability, complaints, exceptions and material decisions.",
    planningGain: "Plan for 20–60% reduction in handling effort for suitable intents; containment may exceed this for simple tasks but must not be the sole KPI. Actual evidence ranges from call-time reductions to 67–75% query handling in disclosed cases.",
    dataControls: "Conversation history, product terms, CRM, account events, entitlement, consent and complaint data. Controls: PII protection, authentication, approved-answer sources, escalation and record retention.",
    gcpArch: "Gemini Enterprise for Customer Experience or Agent Platform, BigQuery, AlloyDB/Spanner, Apigee, Sensitive Data Protection, Model Armor, SCC and Google SecOps.",
    competitive: "Microsoft is strong through Dynamics and Copilot; Salesforce through Service Cloud; AWS through existing contact-centre estates. Google should lead with multimodality, data integration and end-to-end AI security.",
    canonicalProof: "Wells Fargo 245M interactions; Klarna (with caveat); Nubank 55–60% LLM-first. Knowledge/back-office evidence folded in: JPMorgan 3–6 hrs/wk; BBVA ~3 hrs/wk.",
    productIds: ["gemini-enterprise", "agent-engine", "bigquery", "alloydb", "apigee", "model-armor", "secops"],
    caseIds: ["wells-fargo", "klarna", "nubank", "bofa", "commerzbank", "federal-bank", "manulife", "hong-leong", "scotiabank", "discover", "jpmorgan", "bbva", "starling"],
    sourceIds: ["research-file", "canonical"],
    lastReviewed: R,
  },
  {
    id: "software-eng",
    name: "Software engineering & legacy modernisation",
    scores: { value: 5, readiness: 5, complexity: 2, exec: 5, roi: 4 },
    printedComposite: 4.7,
    rationale: "Applies across the enterprise, improves change capacity and avoids immediate customer-decision risk. Hong Leong Bank reports 25% faster development from Gemini Code Assist.",
    current: "Developers interpret legacy code (undocumented COBOL/Java in core systems), search documentation, write tests and wait for reviews and environment provisioning.",
    future: "Coding agents explain code, create migration plans, generate tests and pull requests, detect vulnerabilities and prepare deployment evidence — scanning entire repositories and mapping architectural dependencies.",
    decisionRights: "Engineers remain code and production owners; developers review AI-generated pull requests for architecture, security posture and edge-case logic.",
    planningGain: "Plan for 15–35% end-to-end engineering-capacity improvement, not a claim that code generation itself equals delivery productivity.",
    dataControls: "Source code, dependency graphs, tickets, standards, test data and operational telemetry. Controls: repository permissions, secret scanning, mandatory tests and reviewer approval.",
    gcpArch: "Gemini Code Assist, Gemini Enterprise Agent Platform, GKE, Cloud Build/developer tooling, SCC and Google SecOps.",
    competitive: "Microsoft/GitHub has a strong distribution advantage (GitHub Copilot; AWS Amazon Q). Google must connect coding productivity to cloud modernisation, data platforms and production operations — and position Gemini Code Assist's context window for ingesting entire enterprise codebases.",
    canonicalProof: "Goldman 12,000+ devs, ~20%; Citi 220k code reviews Q1'25.",
    productIds: ["code-assist", "agent-engine", "gke"],
    caseIds: ["goldman-sachs", "citi", "hong-leong", "lloyds"],
    sourceIds: ["research-file", "canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "advisor-copilot",
    name: "Relationship-manager & advisor copilot",
    scores: { value: 5, readiness: 4, complexity: 3, exec: 5, roi: 5 },
    printedComposite: 4.4,
    rationale: "Directly increases customer-facing capacity and improves access to institutional knowledge; Morgan Stanley provides unusually strong adoption evidence.",
    current: "Advisor manually searches research, CRM, portfolios, transactions and prior communications before and after meetings — across dozens of disconnected systems.",
    future: "Research and preparation agents create evidence-linked briefs; a meeting agent captures approved notes; a follow-up agent drafts communications and CRM updates. An orchestrator can use A2A to query market-data and client-history sub-agents, synthesizing responses in seconds.",
    decisionRights: "Advisor approves all client-facing content and recommendations.",
    planningGain: "Plan for 20–40% more time available for customer engagement; validate through preparation time, follow-up latency and customer coverage. Morgan Stanley's adoption establishes feasibility, not a universal gain.",
    dataControls: "CRM, portfolios, product catalogue, research, interaction history, suitability and consent. Controls: entitlements, suitability, communication surveillance, citation and approval.",
    gcpArch: "Agent Platform, Gemini/partner models, BigQuery, AlloyDB, Apigee, Looker, IAM, VPC Service Controls and evaluation. Memory Bank persists client context across sessions under identity/access boundaries.",
    competitive: "Microsoft benefits from productivity-suite integration; Salesforce owns CRM context; Aladdin and Bloomberg own domain workflows; AWS has the Prudential build. Google presents the governed data and agent foundation that integrates them.",
    canonicalProof: "HSBC RM + AI insights; SEB +15%; Morgan Stanley 98% adoption (competitor reference).",
    productIds: ["agent-engine", "adk", "memory-bank", "bigquery", "alloydb", "spanner", "a2a"],
    caseIds: ["morgan-stanley", "prudential", "seb", "hsbc", "blackrock", "ubs", "jpmorgan"],
    sourceIds: ["research-file", "canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "fraud",
    name: "Fraud detection & investigation",
    scores: { value: 5, readiness: 4, complexity: 4, exec: 5, roi: 5 },
    printedComposite: 4.2,
    rationale: "Direct loss prevention and customer protection; high value but requires real-time data, low latency and careful false-positive management.",
    current: "Rules and ML generate alerts; investigators manually assemble transaction, identity and device evidence, conduct external web searches and write disposition reports.",
    future: "Detection models score activity continuously (the “System of Action”: continuous queries on streaming transactions trigger an Investigator Agent that queries history, verifies merchants and compiles a structured dossier before a human is assigned).",
    decisionRights: "Investigators determine disposition; the human analyst becomes an exception-handler reviewing the agent's pre-compiled dossier before authorizing account freeze or release.",
    planningGain: "Plan for 20–50% investigation-effort reduction where evidence retrieval dominates; real-time decision improvements depend heavily on network and behavioural data. Mastercard reports an average 20% fraud-detection improvement for DI Pro modelling.",
    dataControls: "Transactions, device, merchant, identity, network, case and external-risk data. Controls: immutable evidence, low-latency inference, bias testing, false-positive monitoring and investigator sign-off.",
    gcpArch: "BigQuery Continuous Queries → Pub/Sub → ADK agent on Vertex AI Agent Engine → Gemini; Dataflow, Spanner, GKE, SCC and Google SecOps.",
    competitive: "Palantir dominates rapid-deployment overlays; network providers and specialist fraud vendors own proprietary signals. Position ADK + Agent Engine as the native, lower-latency alternative operating where the data resides.",
    canonicalProof: "HSBC 2–4x crime found, 60% fewer false positives; CBA scam losses halved (competitor reference); JPMorgan value “largely fraud.”",
    productIds: ["bigquery", "pubsub", "agent-engine", "adk", "spanner", "secops", "aml-ai"],
    caseIds: ["hsbc", "cba", "mastercard", "block", "nasdaq", "jpmorgan", "temenos"],
    sourceIds: ["research-file", "canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "kyc-onboarding",
    name: "KYC, client onboarding & periodic review",
    scores: { value: 5, readiness: 4, complexity: 4, exec: 5, roi: 3 },
    printedComposite: 3.9,
    rationale: "Large customer-friction and operations opportunity; complex due to jurisdiction rules, entity resolution and evidence requirements.",
    current: "Repeated document requests, manual extraction, fragmented screening and sequential approvals cause long cycle times.",
    future: "Agents classify and validate documents, establish ownership, invoke screening services, identify gaps and assemble a review pack.",
    decisionRights: "Operations resolves exceptions; compliance approves risk classification. No untraceable risk classification.",
    planningGain: "Plan for 30–60% cycle-time reduction in document-heavy cohorts, subject to jurisdiction and exception rates. Bank of Singapore's announced programme targets >30 business days → 15.",
    dataControls: "Identity documents, corporate registries, ownership graphs, sanctions/PEP data, account requirements and jurisdiction policy. Controls: source provenance, expiry, human approval.",
    gcpArch: "Document AI, Agent Platform, Gemini, BigQuery, graph capabilities, Apigee, Workflows, IAM and Sensitive Data Protection.",
    competitive: "Quantexa and compliance specialists are strong in entity resolution; Microsoft and AWS compete on document and agent platforms. Google combines multimodal extraction, data analytics and governed workflow execution.",
    productIds: ["document-ai", "agent-engine", "bigquery", "apigee", "sdp"],
    caseIds: ["bank-of-singapore", "temenos", "finastra", "hong-leong"],
    sourceIds: ["research-file", "canonical"],
    lastReviewed: R,
  },
  {
    id: "credit-underwriting",
    name: "Commercial credit underwriting & annual review",
    scores: { value: 5, readiness: 4, complexity: 4, exec: 5, roi: 3 },
    printedComposite: 3.9,
    rationale: "High revenue and customer-cycle-time impact; human credit authority, explainability and data quality remain constraints. John Hancock's insurance result is the relevant analogue.",
    current: "Analysts collect documents, normalise financials (multi-lingual statements, tax returns, market reports), review policy, model scenarios and write memoranda into legacy platforms.",
    future: "Agents extract financials, validate data, calculate ratios via deterministic tools, compare policy via RAG, identify exceptions and draft an evidence-linked credit memorandum highlighting risks and covenants.",
    decisionRights: "Credit professionals decide terms and approval; the underwriter becomes a strategic editor. US consumer lending: the creditor must provide the specific, accurate principal reasons for adverse action — the risk agent must not generate post-hoc explanations unrelated to actual decision logic.",
    planningGain: "Plan for 30–70% reduction in preparation time for standard cases; decision-cycle gain depends on approval queues and data quality.",
    dataControls: "Applications, statements, bureau and transaction data, collateral, covenants, policy and historical performance. Controls: reason codes, fairness, model validation, maker-checker and override monitoring.",
    gcpArch: "Document AI → Gemini (long context) → AlloyDB (vector store) → Memory Bank for client history; BigQuery, Looker, Apigee, VPC-SC, CMEK and evaluation.",
    competitive: "Microsoft is entrenched via M365 Copilot and Azure AI document capabilities; specialist decision platforms deploy faster. Google wins when proprietary data and policy require a custom, differentiated underwriting workflow.",
    canonicalProof: "AIG >5x faster, 75%→90%+ accuracy (insurance analogue).",
    productIds: ["document-ai", "gemini", "alloydb", "memory-bank", "bigquery"],
    caseIds: ["aig", "john-hancock"],
    sourceIds: ["research-file", "canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "compliance-change",
    name: "Regulatory compliance & policy-change management",
    scores: { value: 4, readiness: 4, complexity: 3, exec: 5, roi: 3 },
    printedComposite: 3.9,
    rationale: "Large knowledge and evidence burden; AI can map regulatory change to policies, controls and obligations while compliance retains approval.",
    current: "Teams read new regulation, identify affected policies, assign changes and gather implementation evidence.",
    future: "Research agent retrieves authoritative text; mapping agent links obligations to policies, controls, systems and owners; validation agent identifies gaps.",
    decisionRights: "Compliance approves interpretations; no delegation of legal-interpretation accountability.",
    planningGain: "Plan for 25–50% reduction in analysis and evidence-assembly effort.",
    dataControls: "Regulatory text, policy library, control inventory, process maps, issues and prior interpretations. Controls: authoritative sources, effective dates, jurisdiction, versioning and legal sign-off.",
    gcpArch: "Agent Platform, Gemini/partner models, BigQuery, enterprise search, Knowledge Catalog, Workflows and immutable logs.",
    competitive: "Microsoft benefits from document estates; ServiceNow and GRC vendors own control workflows. Google should integrate rather than demand replacement.",
    productIds: ["agent-engine", "bigquery", "gemini-enterprise"],
    caseIds: [],
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "investment-research",
    name: "Investment research & market intelligence",
    scores: { value: 4, readiness: 5, complexity: 2, exec: 4, roi: 4 },
    printedComposite: 4.1,
    rationale: "Technically ready and evidence-rich, though total institution-wide economics may be smaller than service or engineering. Berenberg reports 85–90% faster selected content production.",
    current: "Analysts read filings, transcripts, market data and internal notes, then construct models and publish content.",
    future: "Research agents retrieve and compare evidence (a “research swarm”: retrieval agents + a synthesiser + an evaluator verifying citations); deterministic tools calculate; a drafting agent creates initial content.",
    decisionRights: "The analyst challenges and publishes; citation completeness and information barriers enforced.",
    planningGain: "Plan for 40–80% reduction in first-draft and information-retrieval time for selected outputs.",
    dataControls: "Filings, market data, research, models, alternative data and compliance policy. Controls: data licences, citation, information barriers, restricted lists and analyst approval.",
    gcpArch: "Gemini, Agent Platform, BigQuery, Dataflow, Looker, AlloyDB and secure partner-data APIs.",
    competitive: "OpenAI, Anthropic and specialist finance agents (Rogo, Hebbia, Auquan, Finster) are credible. Emphasise multimodal analysis, data scale and flexible model routing.",
    canonicalProof: "DB Lumina 30–45 min/note; Morgan Stanley 98% adoption (competitor reference).",
    productIds: ["gemini", "agent-engine", "bigquery", "alloydb"],
    caseIds: ["deutsche-bank", "berenberg", "morgan-stanley", "bridgewater", "nbim", "lseg", "goldman-sachs", "blackrock"],
    sourceIds: ["research-file", "canonical"],
    lastReviewed: R,
  },
  {
    id: "insurance-ops",
    name: "Insurance claims & underwriting operations",
    scores: { value: 5, readiness: 4, complexity: 4, exec: 4, roi: 4 },
    printedComposite: 4.0,
    rationale: "Large document and decision workload with strong cycle-time opportunities; fraud and customer-fairness controls increase complexity.",
    current: "Manual document review, data re-entry, coverage checking, fraud checks and correspondence.",
    future: "Multimodal agents classify submissions, extract evidence, compare policy, estimate or triage and prepare recommendations.",
    decisionRights: "Licensed adjusters or underwriters approve material decisions.",
    planningGain: "Plan for 30–70% faster intake and preparation, with lower gains for complex exceptions. Manulife and John Hancock provide strong document-cycle evidence.",
    dataControls: "Policies, submissions, images, claims, medical or asset data, fraud signals and external sources. Controls: consent, sensitive data, explainability, bias, coverage evidence and approval thresholds.",
    gcpArch: "Document AI, Gemini multimodality, BigQuery, Agent Platform, GKE, Apigee and Sensitive Data Protection; Confidential Space for sensitive loss data.",
    competitive: "Guidewire, Duck Creek and specialist insurers own workflow context; Azure holds Zurich. Google should power or extend these platforms rather than force greenfield replacement.",
    productIds: ["document-ai", "gemini", "bigquery", "agent-engine", "confidential"],
    caseIds: ["zurich", "aig", "john-hancock", "manulife"],
    sourceIds: ["research-file", "canonical", "fsi-txt"],
    lastReviewed: R,
  },
  {
    id: "treasury-risk",
    name: "Treasury, market & enterprise-risk analysis",
    scores: { value: 5, readiness: 3, complexity: 5, exec: 5, roi: 3 },
    printedComposite: 3.5,
    rationale: "Very high consequence and value, but complex models, real-time data, validation and accountability limit autonomy. HSBC demonstrates value from accelerating the data and scenario layer.",
    current: "Teams reconcile positions, prepare scenarios and manually explain movements across systems.",
    future: "Data agents detect quality issues, scenario agents invoke approved deterministic models, narrative agents explain drivers and assemble packs.",
    decisionRights: "Risk and treasury officers approve assumptions and actions; do not delegate limit, liquidity or capital decisions to an unconstrained LLM.",
    planningGain: "Plan for 20–40% faster preparation and analysis.",
    dataControls: "Positions, cash flows, market data, limits, models, collateral and accounting data. Controls: model inventory, approved scenario engines, lineage, reconciliation and independent validation.",
    gcpArch: "BigQuery, Dataflow, Pub/Sub, GKE, AlloyDB/Spanner, Agent Platform and Looker.",
    competitive: "Data-platform credibility is decisive. HSBC is a direct Google proof point for scalable risk-data and scenario infrastructure.",
    productIds: ["bigquery", "pubsub", "gke", "agent-engine", "spanner"],
    caseIds: ["hsbc", "bny"],
    sourceIds: ["research-file"],
    lastReviewed: R,
  },
  {
    id: "agentic-commerce",
    name: "Payments & agentic commerce",
    scores: null,
    rationale: "Present in the canonical ranking (econ value “Transformational”, readiness “Emerging”) but not scored by the deep-research composite model — shown unranked rather than given invented scores.",
    current: "Payments are initiated by humans through wallets and checkout flows; no trusted standard exists for agent-initiated payment mandates.",
    future: "Agents transact under cryptographically-signed Mandates (Intent, Cart, Payment) with agent identity bound to credentials.",
    decisionRights: "Mandate scopes and spend limits set by the human; verifiable credentials carry the authorization chain.",
    dataControls: "Mandates as W3C Verifiable Credentials; agent identity; payment-network tokens.",
    gcpArch: "AP2, A2A, Vertex.",
    competitive: "OpenAI/Stripe push the proprietary ACP; both card networks joined Google's open AP2 — the neutral-standard position is the differentiator.",
    canonicalProof: "AP2 ecosystem (60+ partners).",
    productIds: ["ap2", "a2a"],
    caseIds: ["payments-standards", "mastercard"],
    sourceIds: ["canonical"],
    lastReviewed: R,
  },
];

const HUB: Hub = {
  cases: CASES,
  workflows: WORKFLOWS,
  vendors: [
    { id: "googlecloud", name: "Google Cloud", cat: "hyperscaler", wins: "Data gravity (BigQuery), Gemini + open + third-party models on Vertex (200+ model Model Garden), sovereign tiers, security (SecOps/Mandiant), ownership of A2A/AP2/MCP interop, TPU economics.", loses: "Where the customer is Microsoft-estate-locked (M365/Azure AD) or wants Copilot ubiquity; weak in exchange/market-infra; fewer incumbent FSI workflow applications.", guidance: "Lead with an open, governed agent-and-data platform; make coexistence with Microsoft 365, Salesforce, ServiceNow and financial ISVs explicit. Anchor the data + agent + security layers even when models are mixed.", caseIds: ["wells-fargo", "hsbc", "deutsche-bank", "citi", "scotiabank", "seb", "starling", "lloyds", "discover", "federal-bank", "hong-leong", "berenberg"], sourceIds: ["canonical", "research-file"], lastReviewed: R },
    { id: "aws", name: "AWS", cat: "hyperscaler", wins: "Bedrock model breadth, incumbency and legacy data gravity (S3), Nasdaq/market-infra, CBA, AgentCore's model/framework neutrality.", loses: "Native gen-AI app suite vs. Google/Microsoft; weaker employee-productivity layer. AWS placed Bedrock Agents Classic into maintenance mode for new customers from 30 July 2026, directing customers to AgentCore — a migration consideration.", guidance: "Emphasise BigQuery-to-agent simplicity, Kubernetes leadership, Gemini multimodality and a coherent analytics-to-AI environment; prove coexistence rather than demanding displacement.", caseIds: ["nasdaq", "cba", "prudential"], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
    { id: "azure", name: "Microsoft Azure", cat: "hyperscaler", wins: "OpenAI access, M365 Copilot distribution, Azure enterprise lock-in (Morgan Stanley, Finastra, LSEG, Temenos, UBS, Commerzbank, Discovery Bank), executive familiarity, Foundry tooling.", loses: "Data-platform neutrality; concentration risk from OpenAI dependency; a workplace-copilot narrative can be insufficient for high-scale transactional and data workloads.", guidance: "“Keep the employee experience where it works.” Contrast workplace assistance with end-to-end workflow execution, data engineering, multi-model flexibility and security operations.", caseIds: ["morgan-stanley", "finastra", "lseg", "temenos", "ubs", "commerzbank", "discovery-bank", "zurich"], sourceIds: ["canonical", "research-file"], lastReviewed: R },
    { id: "openai", name: "OpenAI", cat: "model-lab", wins: "Frontier-model brand, developer mindshare, landmark FSI references (Morgan Stanley, Klarna, BBVA, Nubank); AgentKit/ACP.", loses: "Enterprise architecture depends on cloud, data, identity and integration partners; customers seek model optionality; increasingly distributed through multiple clouds.", guidance: "Position Gemini on capability and economics where appropriate, but make the larger argument about controlled multi-model production.", caseIds: ["morgan-stanley", "klarna", "bbva", "nubank", "jpmorgan", "cba", "goldman-sachs"], sourceIds: ["canonical", "research-file"], lastReviewed: R },
    { id: "anthropic", name: "Anthropic", cat: "model-lab", wins: "“Operating layer for Wall Street” narrative (JPMorgan, Goldman, Citi, AIG, Visa per Fortune, May 2026); enterprise/coding reputation; available on both AWS Bedrock and Google Vertex; safety-first posture resonates in FSI.", loses: "Not an end-to-end FSI stack; relies on hyperscaler security, serving and customer-data systems.", guidance: "Treat Claude as a first-class model option on Google Cloud (data stays in the customer's Google tenancy), reducing model lock-in fear.", caseIds: ["bridgewater", "nbim", "aig", "citi", "jpmorgan", "cba"], sourceIds: ["canonical", "research-file", "fortune-may26"], lastReviewed: R },
    { id: "mistral", name: "Mistral", cat: "model-lab", wins: "HSBC multi-year deal (Dec 2025); open/sovereign options relevant to EU sovereignty and cost.", loses: "Scale versus frontier labs.", guidance: "Relevant to EU sovereignty conversations; hostable via Model Garden.", caseIds: ["hsbc"], sourceIds: ["canonical"], lastReviewed: R },
    { id: "meta-open", name: "Meta Llama / open models (DeepSeek, Kimi, Cohere)", cat: "model-lab", wins: "Cost and sovereignty; fine-tunable for narrow sub-tasks hosted on GKE/TPUs.", loses: "Frontier capability for complex reasoning.", guidance: "Route simple tasks (e.g. entity extraction) to efficient open models within the same governed gateway.", caseIds: [], sourceIds: ["canonical", "fsi-txt"], lastReviewed: R },
    { id: "databricks", name: "Databricks (Mosaic AI)", cat: "data-platform", wins: "Lakehouse data gravity, ML-engineer loyalty, granular control for data-science-heavy shops; Block's fraud agents run on it.", loses: "Less ownership of employee channels and systems of record; runs on hyperscaler infrastructure; premium consumption cost to orchestrate models running on cloud infra.", guidance: "Position BigQuery's serverless operational simplicity and native agent stack; coexist where Databricks is already strategic.", caseIds: ["block", "discovery-bank"], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
    { id: "snowflake", name: "Snowflake (Cortex AI)", cat: "data-platform", wins: "Governed-data footprint, ease of sharing; Cortex AI for Financial Services (Oct 2025) with Anthropic/FactSet/MSCI partners; Snowflake MCP Server; powers CBA's fraud agent.", loses: "Operational/real-time needs often require external services; limited infrastructure layer.", guidance: "Avoid forced displacement: show federated access, BigQuery strengths and Agent Platform as the execution layer.", caseIds: ["cba"], sourceIds: ["canonical", "research-file"], lastReviewed: R },
    { id: "palantir", name: "Palantir (AIP + Ontology + Foundry)", cat: "enterprise-platform", wins: "High-touch ontology, operational decision workflows, executive-level programmes; rapid time-to-value for fragmented legacy estates; exceptional economics (Q3 2025 adjusted gross margin ~84%).", loses: "High perceived cost, services intensity, ontology switching cost and platform concentration.", guidance: "Counter with open architecture and lower concentration; acknowledge Palantir's operationalisation strength. ADK + Agent Engine deliver orchestration natively where the data resides.", caseIds: [], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
    { id: "salesforce-servicenow", name: "Salesforce / ServiceNow (+ SAP, Oracle)", cat: "enterprise-platform", wins: "Ownership of CRM, service and workflow interfaces; embedded context and approval flows; rapid time-to-value for business units.", loses: "Do not own all enterprise data or high-performance AI infrastructure; long-term licensing and lock-in concerns.", guidance: "Partner where they own the workflow; position Google as the data, model, integration and security foundation.", caseIds: [], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
    { id: "nvidia", name: "NVIDIA (+ AMD, CoreWeave)", cat: "silicon", wins: "Near-monopoly on high-end training compute; CUDA ecosystem across all clouds — the neutral arms dealer. CoreWeave challenges on price/availability.", loses: "Primarily infrastructure rather than governed enterprise workflow.", guidance: "Offer NVIDIA GPUs where required while differentiating with TPUs (Ironwood), AI Hypercomputer and managed services; TPU is the credible non-NVIDIA path (Anthropic to access up to 1M TPUs).", caseIds: [], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
    { id: "fsi-isv", name: "FSI ISVs (Temenos, nCino, Finastra, FIS/Fiserv, Murex, Avaloq, Guidewire, Duck Creek, Bloomberg, Aladdin)", cat: "fsi-isv", wins: "Deep domain workflow, regulatory content and installed-base advantage; systems of record.", loses: "May be slow to innovate or restrict model and data choice; most embed Azure OpenAI today.", guidance: "Make Google Cloud the preferred extension and AI runtime rather than reimplementing specialised applications; negotiate model choice into ISV contracts.", caseIds: ["temenos", "finastra", "blackrock"], sourceIds: ["canonical", "research-file"], lastReviewed: R },
    { id: "integrators", name: "Integrators & specialists (Accenture, Deloitte, KPMG; Rackspace, Unit8, Grid Dynamics; Quantexa, Feedzai, Hebbia, Rogo…)", cat: "integrator", wins: "Implementation arm for enterprise platforms; specialist workflow intelligence (entity resolution, research agents, claims AI).", loses: "Combine other vendors' stacks; not a platform.", guidance: "All the big SIs are Claude and Google partners. Tag specialists per use case as partner, compete or component — an AML specialist may compete with a Google-built app yet complement BigQuery, GKE, Gemini and SecOps.", caseIds: [], sourceIds: ["canonical", "research-file", "fsi-txt"], lastReviewed: R },
  ],
  vendorEdges: [
    { from: "googlecloud", to: "anthropic", type: "hosts-model", note: "Claude first-class on Vertex" },
    { from: "googlecloud", to: "mistral", type: "hosts-model", note: "Model Garden" },
    { from: "googlecloud", to: "meta-open", type: "hosts-model", note: "Model Garden (200+ models)" },
    { from: "aws", to: "anthropic", type: "hosts-model", note: "Bedrock — primary partner" },
    { from: "aws", to: "openai", type: "hosts-model", note: "OpenAI models via AWS" },
    { from: "aws", to: "meta-open", type: "hosts-model", note: "Bedrock" },
    { from: "azure", to: "openai", type: "hosts-model", note: "Azure OpenAI — tightly bound" },
    { from: "azure", to: "meta-open", type: "hosts-model" },
    { from: "databricks", to: "anthropic", type: "partners" },
    { from: "snowflake", to: "openai", type: "partners" },
    { from: "snowflake", to: "anthropic", type: "partners", note: "Cortex AI for FSI" },
    { from: "databricks", to: "googlecloud", type: "competes", note: "vs BigQuery/Vertex; also runs on GCP" },
    { from: "snowflake", to: "googlecloud", type: "competes", note: "vs BigQuery; also runs on the clouds" },
    { from: "palantir", to: "aws", type: "partners", note: "AIP sits atop AWS or GCP" },
    { from: "palantir", to: "googlecloud", type: "competes", note: "vs ADK/Agent Engine orchestration" },
    { from: "googlecloud", to: "nvidia", type: "partners", note: "GPUs alongside TPUs" },
    { from: "aws", to: "nvidia", type: "partners" },
    { from: "azure", to: "nvidia", type: "partners" },
    { from: "fsi-isv", to: "azure", type: "partners", note: "Most embed Azure OpenAI today" },
    { from: "googlecloud", to: "aws", type: "competes" },
    { from: "googlecloud", to: "azure", type: "competes" },
    { from: "aws", to: "azure", type: "competes" },
    { from: "salesforce-servicenow", to: "openai", type: "partners" },
    { from: "integrators", to: "palantir", type: "partners", note: "Rackspace runs AIP in regulated environments" },
    { from: "integrators", to: "googlecloud", type: "partners", note: "SIs are Claude AND Google partners" },
    { from: "openai", to: "azure", type: "partners", note: "Aligned but increasingly independent" },
  ],
  products: [
    { id: "tpu", name: "TPU (Ironwood, v7)", layerId: "infra", blurb: "192 GB HBM3E/chip (7.37 TB/s), 4,614 FP8 TFLOPS/chip (first TPU with native FP8), 9,216-chip pods at 42.5 FP8 ExaFLOPS with 1.77 PB shared HBM; Google cites a 10x peak-performance gain over TPU v5p. GA announced Nov 2025; Anthropic to access up to 1M TPUs. Google claims ~44% lower TCO vs. NVIDIA GB200 [company-stated projection]." },
    { id: "gke", name: "GKE + Cloud Run", layerId: "infra", blurb: "Portable, resilient runtime for custom APIs, deterministic services and open-model workloads. DB Lumina runs on GKE. 42+ regions, 127 zones." },
    { id: "confidential", name: "Confidential Computing", layerId: "infra", blurb: "Confidential Space / Confidential GKE Nodes: data cryptographically isolated in use — invisible even to cloud administrators. Unlocks cross-institutional collaboration previously blocked by compliance." },
    { id: "bigquery", name: "BigQuery (+ Continuous Queries)", layerId: "data", blurb: "Serverless unified analytics; vector search; Gemini integration. Continuous Queries evaluate streaming transactions in real time and publish events that trigger agents — merging the analytical and operational planes." },
    { id: "alloydb", name: "AlloyDB AI", layerId: "data", blurb: "PostgreSQL-compatible; ScaNN index scales to 10B vectors; up to 6x faster vector queries than PostgreSQL HNSW." },
    { id: "spanner", name: "Spanner", layerId: "data", blurb: "Globally consistent transactions; vector search to trillions of vectors; 99.999% availability." },
    { id: "biglake", name: "BigLake + Dataplex", layerId: "data", blurb: "Unifies lakes and warehouses; automated data-quality rules and lineage — the antidote to the Scotiabank 33%-accuracy failure mode." },
    { id: "pubsub", name: "Pub/Sub + Dataflow", layerId: "data", blurb: "Event backbone of the “System of Action”: continuous-query hits publish payloads that invoke investigator agents." },
    { id: "gemini", name: "Gemini + Vertex AI + Model Garden", layerId: "gateway", blurb: "Gemini 2.5/3 with a 1M-token context window (Wells Fargo's CIO praised it for unstructured data); Model Garden with 200+ models including Claude (first-class), Llama, Mistral, Gemma — the “and, not or” model story." },
    { id: "code-assist", name: "Gemini Code Assist", layerId: "gateway", blurb: "Coding agent for legacy modernisation; Hong Leong reports 25% faster development." },
    { id: "document-ai", name: "Document AI", layerId: "gateway", blurb: "Multimodal document extraction for credit, KYC, claims and trade operations." },
    { id: "adk", name: "Agent Development Kit (ADK)", layerId: "agents", blurb: "Open, code-first multi-agent scaffolding (~100 lines of code, 200+ models)." },
    { id: "agent-engine", name: "Vertex AI Agent Engine", layerId: "agents", blurb: "Managed secure runtime: lifecycle, tool orchestration, sessions, eval/monitoring/tracing, sandboxing." },
    { id: "gemini-enterprise", name: "Gemini Enterprise", layerId: "agents", blurb: "Launched Oct 9, 2025 (rebrand of Agentspace); “the new front door for AI in the workplace”; permission-aware enterprise search over M365/ServiceNow/SAP/Salesforce; list pricing ~$21–$30/seat/month. Google's 2026 direction: Gemini Enterprise Agent Platform is the forward path for services previously associated with Vertex AI." },
    { id: "a2a", name: "A2A + MCP protocols", layerId: "agents", blurb: "A2A: open agent-to-agent interop via AgentCards (JSON over HTTP POST/gRPC) regardless of framework; MCP connects models to tools/data. Google authored/co-authored the key open agent protocols." },
    { id: "ap2", name: "AP2 (Agent Payments Protocol)", layerId: "agents", blurb: "Open, payment-agnostic standard with cryptographically-signed Mandates as W3C Verifiable Credentials; 60+ launch partners; both card networks joined; x402 stablecoin extension; Apache 2.0, v0.2.0 (Apr 2026)." },
    { id: "memory-bank", name: "Memory Bank", layerId: "agents", blurb: "Persistent, per-user scoped memory with asynchronous consolidation, governed by IAM conditions — the cure for agent “amnesia” in wealth copilots." },
    { id: "model-armor", name: "Agent Gateway + Model Armor", layerId: "agents", blurb: "Governance for prompts and agent traffic: prompt-injection, sensitive-data-leak and harmful-content protections." },
    { id: "secops", name: "Google Unified Security (SecOps + Mandiant)", layerId: "security", blurb: "SIEM/SOAR + Mandiant threat intelligence + VirusTotal + Gemini/SecLM with agentic alert triage; SCC discovers AI assets and monitors agent interactions." },
    { id: "sovereign", name: "Sovereign Cloud tiers", layerId: "security", blurb: "Data Boundary (residency + external key management), Dedicated (independent operator), Air-Gapped; partner-operated variants incl. T-Systems (Germany) and Thales/S3NS (France)." },
    { id: "sdp", name: "IAM · VPC-SC · CMEK · Sensitive Data Protection", layerId: "security", blurb: "Least privilege for every person, service and agent; network isolation; encryption control; DLP masking before model interaction." },
    { id: "eval", name: "Vertex AI Evaluation + Explainable AI + Model Cards", layerId: "eval", blurb: "Eval gates decide what reaches production; joined with bank-specific model-risk standards (SR 26-2, EU AI Act evidence), not a substitute for them." },
    { id: "apigee", name: "Apigee API management", layerId: "gateway", blurb: "Agents never get unrestricted core-system access: APIs encapsulate permitted actions, validation, throttling, consent, transaction limits and audit fields." },
    { id: "aml-ai", name: "AML AI", layerId: "gateway", blurb: "Google's anti-money-laundering models — the HSBC Dynamic Risk Assessment engine." },
  ],
  architectureLayers: [
    { id: "infra", name: "1 · Sovereign infrastructure & compute", story: "Financial models need massive scale; regulation demands absolute privacy. Custom TPUs and NVIDIA GPUs on GKE give elastic training and inference.", fsiRelevance: "Confidential Computing cryptographically isolates data in use — invisible even to cloud administrators — unlocking cross-institutional fraud detection previously blocked by compliance. TPU economics hedge NVIDIA dependency.", proof: "Ironwood specs [VERIFIED, Google-stated]; ~44% lower TCO vs GB200 is a company projection; Anthropic to access up to 1M TPUs.", productIds: ["tpu", "gke", "confidential"], sourceIds: ["canonical", "fsi-txt"] },
    { id: "data", name: "2 · Data gravity & governance", story: "Agents are ineffective without real-time, governed data. Spanner holds globally consistent transactions; BigLake unifies lakes and warehouses; Dataplex enforces quality and lineage.", fsiRelevance: "BigQuery Continuous Queries shift fraud/AML from overnight batch to event-driven, real-time defense — the analytical and operational planes merge.", proof: "HSBC risk data on GCS/Dataflow/BigQuery; Scotiabank's 33%→96% lesson is the case for governed data quality.", productIds: ["bigquery", "alloydb", "spanner", "biglake", "pubsub"], sourceIds: ["canonical", "fsi-txt", "research-file"] },
    { id: "gateway", name: "3 · The AI gateway & frontier intelligence", story: "Vertex AI is the centralized, governed gateway: Gemini beside 200+ open and third-party models, with evaluation before production.", fsiRelevance: "Model optionality prevents lock-in: route SWIFT entity extraction to a cheap open model, reserve Gemini's 1M-token context for 500-page syndicated loan agreements — one governance framework throughout.", proof: "Citi runs Gemini alongside Claude; Wells Fargo's CIO praised the 1M window for unstructured data.", productIds: ["gemini", "code-assist", "document-ai", "apigee", "aml-ai"], sourceIds: ["canonical", "fsi-txt"] },
    { id: "agents", name: "4 · Agent orchestration & autonomous execution", story: "ADK provides scaffolding; Agent Engine the secure managed runtime; A2A/AP2/MCP the open interop; Gemini Enterprise the workplace front door; Agent Gateway + Model Armor the governance.", fsiRelevance: "A Wealth Orchestrator discovers and delegates to sub-agents via A2A AgentCards while Memory Bank persists client context under IAM boundaries — no custom microservices routing.", proof: "Prudential's 3–4-week AWS benchmark is the number to beat; AP2's 60+ partners are the payments beachhead.", productIds: ["adk", "agent-engine", "gemini-enterprise", "a2a", "ap2", "memory-bank", "model-armor"], sourceIds: ["canonical", "fsi-txt"] },
    { id: "security", name: "5 · Security & sovereignty (the shield)", story: "SCC and SecOps monitor the whole estate; DLP masks sensitive data before models see it; IAM and zero-trust halt prompt-injected agents; Chronicle logs every sequence for audit.", fsiRelevance: "Sovereign tiers (Data Boundary / Dedicated / Air-Gapped, incl. T-Systems and Thales/S3NS) answer EU AI Act, DORA and residency head-on.", proof: "Google Unified Security: SecOps + Mandiant + VirusTotal + Gemini/SecLM with agentic alert triage.", productIds: ["secops", "sovereign", "sdp"], sourceIds: ["canonical", "fsi-txt"] },
    { id: "eval", name: "6 · Evaluation & responsible AI", story: "Vertex AI Evaluation, observability and model cards make eval the gating function for production — the pattern Morgan Stanley and Nubank prove.", fsiRelevance: "SR 26-2 and EU AI Act explainability demand model-risk evidence; eval artifacts are that evidence.", proof: "Eval-driven development recurs across Morgan Stanley, Nubank and OpenAI's own practice.", productIds: ["eval"], sourceIds: ["canonical", "research-file"] },
  ],
  archPaths: [
    { workflowId: "customer-service", label: "Customer service", productIds: ["gemini", "agent-engine", "gemini-enterprise", "bigquery", "alloydb", "apigee", "model-armor", "sdp", "eval"], flow: "Channel → Apigee → Model Armor → Agent Engine → Gemini (grounded in BigQuery/AlloyDB) → human escalation, with eval gates and audit logs." },
    { workflowId: "credit-underwriting", label: "Credit", productIds: ["document-ai", "gemini", "alloydb", "memory-bank", "bigquery", "eval", "sdp"], flow: "Document AI → Gemini (long context) → deterministic ratio tools → AlloyDB vectors + Memory Bank client history → evidence-linked memo → credit officer." },
    { workflowId: "advisor-copilot", label: "Wealth", productIds: ["adk", "agent-engine", "a2a", "memory-bank", "spanner", "bigquery", "eval"], flow: "ADK orchestrator → A2A to market-data & client-history sub-agents → Spanner + Memory Bank → advisor approves; trades queued for execution." },
    { workflowId: "fraud", label: "Fraud / AML", productIds: ["bigquery", "pubsub", "adk", "agent-engine", "gemini", "secops", "aml-ai"], flow: "BigQuery Continuous Queries → Pub/Sub → Investigator Agent (ADK on Agent Engine) → Gemini dossier → human analyst disposition; SecOps logs all." },
    { workflowId: "investment-research", label: "Research", productIds: ["gemini", "agent-engine", "bigquery", "alloydb", "gke", "eval"], flow: "Research swarm: retrieval agents → synthesiser → citation evaluator; pgvector-style stores on AlloyDB; GKE microservices (the DB Lumina pattern)." },
    { workflowId: "insurance-ops", label: "Insurance", productIds: ["document-ai", "gemini", "confidential", "bigquery", "agent-engine", "sdp"], flow: "Multimodal intake (Document AI + Gemini) inside Confidential Space → policy comparison → triage recommendation → licensed adjuster approves." },
  ],
  regulations: [
    { id: "eu-ai-act", name: "EU AI Act", region: "EU", detail: "Credit scoring and insurance-risk pricing are high-risk (Annex III §5(b) and §6). Penalties up to €15M or 3% of global turnover. Provider vs. deployer matters: banks building their own credit models are “providers” (heaviest tier).", dates: [ { date: "2025-02-02", label: "Prohibited practices apply" }, { date: "2025-08-02", label: "GPAI-model obligations apply" }, { date: "2026-08-02", label: "Full high-risk obligations apply" }, { date: "2027-08-02", label: "Product-embedded systems in scope" } ], archImplication: "Explainability, human oversight (Art. 14), risk management (Art. 9) and data residency drive sovereign cloud + eval + audit-trail requirements.", sourceIds: ["canonical"] },
    { id: "sr-26-2", name: "Federal Reserve SR 26-2", region: "US", detail: "Issued April 2026, superseding SR 11-7 / SR 21-8 for model-risk management. The OCC has stated generative/agentic AI may fall outside the revised guidance's scope.", dates: [{ date: "2026-04-01", label: "SR 26-2 issued, supersedes SR 11-7/21-8" }], archImplication: "Model-risk evidence generation (evaluation artifacts, monitoring, model cards) becomes the deliverable, not an afterthought.", sourceIds: ["canonical"] },
    { id: "cfpb", name: "US adverse-action explanation (consumer lending)", region: "US", detail: "A creditor must provide the specific and accurate principal reasons for an adverse action; a complex or opaque algorithm does not remove that obligation.", dates: [], archImplication: "Explanation must be architected into the decision system — a risk agent must never generate post-hoc narratives unrelated to actual decision logic.", sourceIds: ["research-file"] },
    { id: "dora", name: "DORA", region: "EU", detail: "Digital operational resilience for the financial sector.", dates: [], archImplication: "Operational-resilience evidence across the AI estate; vendor-concentration analysis.", sourceIds: ["canonical"] },
    { id: "gdpr", name: "GDPR", region: "EU", detail: "Data protection baseline for personal data in AI systems.", dates: [], archImplication: "Data minimisation and purpose limitation → PII tokenization before model calls (the Wells Fargo pattern).", sourceIds: ["canonical"] },
    { id: "mas-rbi", name: "MAS FEAT / Veritas · RBI guidance", region: "APAC / India", detail: "Singapore's fairness/ethics/accountability/transparency framework and Veritas methodology; RBI guidance for India.", dates: [], archImplication: "Fairness testing and documentation folded into the evaluation layer for APAC/India deployments.", sourceIds: ["canonical"] },
    { id: "boe", name: "Bank of England — frontier-agent examination", region: "UK", detail: "The Bank of England has begun examining financial-stability risks involving frontier agents; financial authorities are assessing AI-related operational, cyber and market risks.", dates: [], archImplication: "Every agent needs a distinct identity, least-privilege permissions, transaction limits, revocation and full action logs.", sourceIds: ["research-file"] },
  ],
  sources: [
    { id: "canonical", name: "Canonical hub file — Financial Services AI & Agentic Transformation Knowledge Hub, Google Cloud India (Aug 2026)", kind: "research-file", note: "Wins on facts, figures, labels and vendor attribution." },
    { id: "research-file", name: "Deep-research report (5 Aug 2026)", kind: "research-file", note: "Wins on scoring, frameworks and structure. Citation tokens were stripped; where no named source survived, claims are marked “Source not captured in research file.”" },
    { id: "fsi-txt", name: "FSI_.txt — Global FSI AI & Agentic Transformation Hub", kind: "research-file", note: "Contributes case deep-dives and frontier-architecture narratives. Carries no named external citations." },
    { id: "bloomberg-nov24", name: "Bloomberg, Nov 28, 2024 (CBA outcomes)", kind: "press" },
    { id: "venturebeat-apr25", name: "VentureBeat, Apr 2025 (Wells Fargo Fargo interactions)", kind: "press" },
    { id: "klarna-openai-feb24", name: "Klarna/OpenAI joint release, Feb 2024", kind: "vendor" },
    { id: "ms-release", name: "Morgan Stanley press release (Assistant adoption)", kind: "primary" },
    { id: "openai-case", name: "OpenAI case study (Morgan Stanley document access)", kind: "vendor" },
    { id: "fortune-may26", name: "Fortune, May 2026 (“operating layer for Wall Street”)", kind: "press" },
    { id: "not-captured", name: "Source not captured in research file", kind: "not-captured", note: "The deep-research file carried a citation token here but no named source survived extraction. The claim is retained and flagged rather than silently dropped." },
  ],
  proofPoints: [
    { id: "mass-adoption", message: "Mass customer adoption", leadCaseIds: ["wells-fargo"], competitorCaseIds: ["bofa"] },
    { id: "employee-adoption", message: "Employee adoption", leadCaseIds: ["citi", "goldman-sachs"], competitorCaseIds: ["morgan-stanley", "jpmorgan", "bbva"] },
    { id: "faster-research", message: "Faster research", leadCaseIds: ["deutsche-bank", "berenberg"], competitorCaseIds: ["morgan-stanley", "lseg"] },
    { id: "platform-scale", message: "AI-platform scale", leadCaseIds: ["lloyds"], competitorCaseIds: ["jpmorgan", "bny"] },
    { id: "cs-automation", message: "Customer-service automation", leadCaseIds: ["wells-fargo", "hong-leong", "discover", "scotiabank"], competitorCaseIds: ["klarna", "commerzbank", "nubank", "bofa"] },
    { id: "fincrime", message: "Financial-crime performance", leadCaseIds: ["hsbc"], competitorCaseIds: ["cba", "mastercard", "nasdaq"] },
    { id: "doc-cycle", message: "Document-cycle reduction", leadCaseIds: ["hong-leong"], competitorCaseIds: ["john-hancock", "manulife", "zurich", "aig"] },
    { id: "india-story", message: "India data-and-security story", leadCaseIds: ["federal-bank"], competitorCaseIds: [] },
    { id: "model-optionality", message: "Model optionality", leadCaseIds: ["citi", "wells-fargo"], competitorCaseIds: ["bny", "goldman-sachs", "jpmorgan"] },
    { id: "wealth", message: "Wealth & advisor copilots", leadCaseIds: ["seb", "deutsche-bank"], competitorCaseIds: ["morgan-stanley", "prudential", "ubs", "blackrock"] },
  ],
};

export default HUB;
