import type { Confidence, Datum, Evidence, Product } from "./types";

/**
 * Research dataset — 14 current-generation earbuds, US launch pricing,
 * snapshot 1 Oct 2026. Every value cites ids from ./sources. `null` means our
 * sources did not establish the value; it is never guessed.
 *
 * Metric definitions (see ./metrics and RESEARCH_BRIEF.md §2):
 *  price           US launch MSRP, USD (manufacturer / launch coverage)
 *  anc             SoundGuys Active Noise Cancelling score, 0–10 (= avg perceived-loudness reduction ÷ 10)
 *  batteryClaim    manufacturer hours, buds only, ANC on
 *  batteryMeasured RTINGS continuous playback hours
 *  comfort         SoundGuys Comfort & fit rating, 0–10 (subjective)
 *  weight          grams per earbud
 */

function d<T>(value: T, evidence: Evidence, sources: string[], confidence: Confidence = "high", note?: string): Datum<T> {
  return { value, evidence, sources, confidence, note };
}

function unknown<T>(note?: string, sources: string[] = [], evidence: Evidence = "manufacturer"): Datum<T> {
  return { value: null, evidence, sources, confidence: "low", note };
}

const SG_SCORE = "SoundGuys ANC score";

export const PRODUCTS: Product[] = [
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "airpods-pro-3",
    brand: "Apple",
    name: "AirPods Pro 3",
    short: "AirPods Pro 3",
    generation: "3rd-generation AirPods Pro",
    released: "Sep 2025",
    metrics: {
      price: d(249, "manufacturer", ["whf-app3-price", "sg-app3-news"]),
      anc: d(9.0, "measured", ["sg-app3", "sg-app3-anc"], "high", "90% average perceived-loudness reduction — the highest SoundGuys had measured in earbuds."),
      batteryClaim: d(8, "manufacturer", ["apple-app3-specs"], "high", "7.5 h with Spatial Audio head tracking; 6.5 h with heart-rate sensing."),
      batteryMeasured: d(9, "measured", ["rt-app3", "rt-ap4-vs-app3"], "medium"),
      comfort: d(7.0, "reviewer", ["sg-app3"], "medium"),
      weight: d(5.55, "manufacturer", ["apple-app3-specs"]),
    },
    features: {
      ipRating: d("IP57", "manufacturer", ["apple-app3-specs"], "high", "Earbuds and case. Apple: resistance is not permanent and can diminish over time."),
      multipoint: unknown("Standard two-device multipoint is not documented in our sources."),
      ecosystemSwitching: d("Apple automatic switching between Apple devices on the same Apple Account", "manufacturer", ["apple-switching"], "medium"),
      transparency: d("yes", "manufacturer", ["apple-controls"], "high", "Transparency and Adaptive Audio, switched by press-and-hold."),
      wirelessCharging: d("yes", "manufacturer", ["sg-app3-news"], "medium", "MagSafe charging case with USB-C."),
      fitAid: d("tips-only", "manufacturer", ["sg-app3-news"], "medium", "Five ear-tip sizes; no wing or hook."),
      controls: d("Stem force sensor: press for playback and calls, swipe for volume, hold for listening modes", "manufacturer", ["apple-controls"]),
      heartRate: d("yes", "manufacturer", ["apple-app3-specs"]),
      ios: d("full", "manufacturer", ["apple-controls", "apple-switching"], "medium"),
      android: unknown("Android feature support not documented in our sources. RTINGS notes the mic is less consistent on non-Apple devices.", ["rt-ap4-vs-app3"]),
      caseTotalHours: d(24, "manufacturer", ["sg-app3-news"], "medium"),
    },
    notes: [
      { topic: "commute", kind: "strength", text: "SoundGuys measured the strongest earbud noise cancelling it had tested: about 90% less perceived outside noise.", evidence: "measured", sources: ["sg-app3-anc"] },
      { topic: "gym", kind: "strength", text: "IP57 earbuds and case, plus workout heart-rate sensing.", evidence: "manufacturer", sources: ["apple-app3-specs"] },
      { topic: "gym", kind: "limitation", text: "One comparison reports the tips can slip a little as sweat builds up; there is no wing or hook.", evidence: "reviewer", sources: ["ts2-compare"] },
      { topic: "calls", kind: "strength", text: "Tom's Guide found voice isolation on calls held up on busy Manhattan streets.", evidence: "reviewer", sources: ["tg-app3"] },
      { topic: "calls", kind: "limitation", text: "RTINGS says the mic sounds better with iOS and is less consistent on non-Apple devices.", evidence: "measured", sources: ["rt-ap4-vs-app3"] },
      { topic: "office", kind: "limitation", text: "Device switching relies on Apple's account-based switching; standard multipoint for a Windows laptop + Android phone isn't documented.", evidence: "manufacturer", sources: ["apple-switching"] },
      { topic: "travel", kind: "strength", text: "RTINGS measured about 9 h of continuous playback with the case adding roughly two more charges.", evidence: "measured", sources: ["rt-app3"] },
      { topic: "sound", kind: "context", text: "RTINGS comparison data describes a warm-leaning profile (bass about +1 dB, treble about −3 dB).", evidence: "measured", sources: ["rt-app-vs-app3"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "airpods-5",
    brand: "Apple",
    name: "AirPods 5 (USB-C case)",
    short: "AirPods 5",
    generation: "5th-generation AirPods, open-fit with ANC",
    released: "Sep 2026",
    priceNote: "$149 with the Wireless Charging Case, which also lifts ANC-on battery to 5 h and adds stem volume swipe.",
    metrics: {
      price: d(129, "manufacturer", ["apple-ap5-news", "ecoustics-ap5"]),
      anc: d(5.9, "derived", ["sg-ap5"], "medium", `SoundGuys published a 59% average reduction; converted to the ${SG_SCORE} scale (÷10). Weak below 500 Hz.`),
      batteryClaim: d(4, "manufacturer", ["apple-ap5-specs"], "high", "USB-C model. 5 h for the Wireless Charging Case model."),
      batteryMeasured: unknown("RTINGS listed AirPods 5 as still being tested.", ["rt-pipeline"], "measured"),
      comfort: unknown("No SoundGuys comfort score captured. SoundGuys: the fit 'makes or breaks the entire experience'.", ["sg-ap5"], "reviewer"),
      weight: d(4.3, "manufacturer", ["apple-ap5-specs"]),
    },
    features: {
      ipRating: d("IP57", "manufacturer", ["apple-ap5-specs"], "high", "Up from IP54 on AirPods 4."),
      multipoint: unknown("Standard multipoint is not documented in our sources."),
      ecosystemSwitching: unknown("Apple's automatic switching applies to 'supported AirPods models'; AirPods 5 support isn't confirmed in our sources.", ["apple-switching"]),
      transparency: d("yes", "manufacturer", ["apple-ap5-news", "apple-modes"], "high", "Improved Transparency plus Adaptive Audio."),
      wirelessCharging: d("no", "manufacturer", ["apple-ap5-specs"], "high", "USB-C model only. The $149 Wireless Charging Case model works with Qi and Apple Watch chargers."),
      fitAid: d("open-fit", "reviewer", ["sg-ap5"], "medium", "One-size open fit, no ear tips."),
      controls: d("Stem force sensor; volume swipe only on the Wireless Charging Case model", "manufacturer", ["apple-ap5-news", "apple-modes"]),
      heartRate: unknown("Not mentioned in our sources."),
      ios: d("full", "manufacturer", ["apple-ap5-news"], "medium"),
      android: unknown("Android feature support not documented in our sources."),
      caseTotalHours: d(20, "manufacturer", ["apple-ap5-specs"], "high", "22 h for the Wireless Charging Case model."),
    },
    notes: [
      { topic: "commute", kind: "limitation", text: "SoundGuys: ANC works mainly from about 1–9 kHz and struggles below 500 Hz, so engine and airplane rumble still get through.", evidence: "measured", sources: ["sg-ap5"] },
      { topic: "outdoor", kind: "context", text: "The unsealed open fit lets more outside sound in than sealed buds. That is not a safety guarantee — stay alert near traffic.", evidence: "reviewer", sources: ["sg-ap5", "apple-safety"] },
      { topic: "gym", kind: "strength", text: "IP57 rating, a step up from AirPods 4's IP54.", evidence: "manufacturer", sources: ["apple-ap5-specs"] },
      { topic: "gym", kind: "limitation", text: "One-size open fit: security depends heavily on your ear shape.", evidence: "reviewer", sources: ["sg-ap5"] },
      { topic: "travel", kind: "limitation", text: "4 h ANC-on battery per charge (5 h on the wireless-case model) is the shortest claim in this set.", evidence: "manufacturer", sources: ["apple-ap5-specs"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "powerbeats-pro-2",
    brand: "Beats",
    name: "Powerbeats Pro 2",
    short: "Powerbeats Pro 2",
    generation: "2nd-generation Powerbeats Pro",
    released: "Feb 2025",
    priceNote: "$199.95 at Amazon on 24 Sep 2026.",
    metrics: {
      price: d(249.99, "manufacturer", ["cc-pbp2"], "medium"),
      anc: d(8.3, "derived", ["sg-app3-vs-pbp2"], "medium", `SoundGuys measured ~83% average reduction; converted to the ${SG_SCORE} scale (÷10).`),
      batteryClaim: d(8, "manufacturer", ["utah-pbp2"], "medium", "Retailer reproduction of the Beats spec. 10 h with ANC off."),
      batteryMeasured: d(5.9, "measured", ["rt-pbp2"]),
      comfort: d(8.0, "reviewer", ["sg-pbp2"], "medium", "TechGearLab disagrees sharply: 4.5/10, the narrow hook doesn't suit everyone."),
      weight: unknown("Sources conflict: 8.7 g (retailer spec sheet) vs 4.35 g (review). Not plotted.", ["utah-pbp2", "hc-pbp2"]),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["utah-pbp2"], "medium"),
      multipoint: d("no", "reviewer", ["hifide-beats"], "medium", "Reported: no simultaneous connection to two devices."),
      ecosystemSwitching: d("Apple H2 features with Apple devices (e.g. hands-free Siri, Find My)", "reviewer", ["hh-pbp2"], "medium"),
      transparency: d("yes", "reviewer", ["hc-pbp2"], "medium"),
      wirelessCharging: d("yes", "manufacturer", ["utah-pbp2"], "medium", "Qi-certified chargers; USB-C."),
      fitAid: d("ear-hook", "measured", ["rt-pbp2", "hc-pbp2"], "high", "Nickel-titanium ear hook."),
      controls: d("Physical buttons: 'b' button and volume rocker on each bud — usable with sweaty hands", "reviewer", ["hc-pbp2"], "medium"),
      heartRate: d("yes", "manufacturer", ["cc-pbp2", "hh-pbp2"]),
      ios: d("full", "reviewer", ["hh-pbp2"], "medium"),
      android: d("limited", "reviewer", ["hh-pbp2"], "medium", "Beats app on Android; heart-rate tracking must be started manually; less integrated."),
      caseTotalHours: d(36, "manufacturer", ["utah-pbp2"], "medium"),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "RTINGS: the ear hooks keep them stable.", evidence: "measured", sources: ["rt-pbp2"] },
      { topic: "gym", kind: "strength", text: "Physical buttons and a volume rocker work reliably with wet or sweaty hands.", evidence: "reviewer", sources: ["hc-pbp2"] },
      { topic: "gym", kind: "limitation", text: "Hook comfort is ear-dependent: TechGearLab scored comfort & fit 4.5/10 while SoundGuys gave 8.0.", evidence: "reviewer", sources: ["tgl-pbp2", "sg-pbp2"] },
      { topic: "calls", kind: "limitation", text: "RTINGS rates the mic middling: handles steady noise but struggles with sudden loud sounds.", evidence: "measured", sources: ["rt-pbp2"] },
      { topic: "travel", kind: "limitation", text: "RTINGS measured 5.9 h continuous — well short of the 8 h ANC-on claim.", evidence: "measured", sources: ["rt-pbp2"] },
      { topic: "general", kind: "context", text: "RTINGS: AirPods Pro 3 suit most people better unless you use Android or have hard-to-fit ears.", evidence: "reviewer", sources: ["rt-pbp2"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "pixel-buds-pro-2",
    brand: "Google",
    name: "Pixel Buds Pro 2",
    short: "Pixel Buds Pro 2",
    generation: "2nd-generation Pixel Buds Pro",
    released: "Aug 2024",
    metrics: {
      price: d(229, "manufacturer", ["aa-pbp2-qi", "9to5-mbg2026"]),
      anc: d(8.0, "measured", ["sg-pbp2g"], "medium"),
      batteryClaim: d(8, "manufacturer", ["google-pbp2-specs"]),
      batteryMeasured: unknown("An RTINGS figure (~7 h 55 min) surfaced but could not be verified. Not plotted.", ["rt-pixel"], "measured"),
      comfort: d(8.5, "reviewer", ["sg-pbp2g"], "medium"),
      weight: d(4.7, "manufacturer", ["google-pbp2-specs"], "high", "With medium ear tip."),
    },
    features: {
      ipRating: d("IP54", "manufacturer", ["google-pbp2-specs"], "high", "Case is IPX4."),
      multipoint: d("yes", "reviewer", ["sg-pbp2-review", "aa-pbp2-qi"], "medium"),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "reviewer", ["ob-pixel"], "medium", "Conversation Detection switches to Transparency when you speak."),
      wirelessCharging: d("yes", "manufacturer", ["aa-pbp2-qi"], "high", "Qi, up to 5 W."),
      fitAid: d("wing-or-fin", "manufacturer", ["google-pbp2-store"], "high", "Twist-to-adjust stabilizer."),
      controls: d("Touch: tap, swipe for volume, long-press for ANC or Gemini", "reviewer", ["ob-pixel"], "medium"),
      heartRate: unknown(),
      ios: unknown("iPhone feature support not documented in our sources."),
      android: d("full", "manufacturer", ["9to5-mbg2026", "google-pbp2-store"], "medium"),
      caseTotalHours: d(30, "manufacturer", ["google-pbp2-specs"]),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "Twist-to-adjust stabilizer locks the buds in for workouts or loosens for all-day comfort.", evidence: "manufacturer", sources: ["google-pbp2-store"] },
      { topic: "office", kind: "strength", text: "Reviewers found them more comfortable and stable than AirPods Pro 3 for long sessions; SoundGuys comfort 8.5/10.", evidence: "reviewer", sources: ["ts2-compare", "sg-pbp2g"] },
      { topic: "calls", kind: "limitation", text: "RTINGS: the mic is quite poor in noisy environments.", evidence: "measured", sources: ["rt-pixel"] },
      { topic: "general", kind: "context", text: "Google shipped an ANC update in Sep 2026 that adapts to how the buds sit; lab results predate it.", evidence: "manufacturer", sources: ["9to5-mbg2026"] },
      { topic: "sound", kind: "context", text: "Pocket-lint found the sound 'surprisingly lackluster'.", evidence: "reviewer", sources: ["pocketlint-pixel"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "sony-wf-1000xm6",
    brand: "Sony",
    name: "WF-1000XM6",
    short: "Sony XM6",
    generation: "6th-generation 1000X earbuds",
    released: "Feb 2026",
    metrics: {
      price: d(329.99, "manufacturer", ["prn-xm6"]),
      anc: d(8.8, "measured", ["sg-xm6", "sg-xm6-review"], "high", "88% average perceived-loudness reduction."),
      batteryClaim: d(8, "manufacturer", ["sony-xm6-mea", "sg-xm6-review"], "high", "One Sony UK rendering listed 5 h — most likely the call-time figure."),
      batteryMeasured: d(8.6, "measured", ["rt-xm6"], "medium", "Single rendering. SoundGuys measured 9 h 41 min under its own protocol."),
      comfort: d(8.5, "reviewer", ["sg-xm6"], "medium"),
      weight: d(6.5, "manufacturer", ["sony-xm6-specs"], "high", "With M tips."),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["sony-xm6-specs"], "high", "Earbuds only; the case is not water resistant."),
      multipoint: d("yes", "manufacturer", ["ss-xm6-multipoint"], "low", "Third-party Q&A: two devices; LDAC is unavailable while multipoint is on."),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["sony-xm6-press"], "high", "Ambient Sound mode; Adaptive Sound Control; Speak-to-Chat."),
      wirelessCharging: d("yes", "manufacturer", ["sony-xm6-specs"], "high", "Qi."),
      fitAid: d("tips-only", "measured", ["rt-xm6"], "high", "Memory-foam tips, no fins."),
      controls: d("Touch sensors, assignable per bud in the Sound Connect app", "manufacturer", ["sony-xm6-touch"]),
      heartRate: unknown(),
      ios: d("full", "manufacturer", ["sony-xm5-start"], "low", "Sound Connect app is on iOS and Android (documented for the XM5). LDAC needs Android."),
      android: d("full", "manufacturer", ["sony-xm5-start", "sony-xm6-mea"], "low"),
      caseTotalHours: d(24, "manufacturer", ["sony-xm6-mea"]),
    },
    notes: [
      { topic: "commute", kind: "strength", text: "RTINGS: outstanding isolation, beating the XM5 especially in the bass range; it edges the Bose QC Ultra 2nd Gen on ANC.", evidence: "measured", sources: ["rt-xm6", "rt-bose-vs-xm6"] },
      { topic: "commute", kind: "context", text: "TechRadar called the noise cancelling 'middling' — reviewers disagree.", evidence: "reviewer", sources: ["tr-xm6"] },
      { topic: "gym", kind: "limitation", text: "No fins; RTINGS says the bulkier body can pop out of smaller ears. TechRadar also noted fit issues.", evidence: "measured", sources: ["rt-xm6", "tr-xm6"] },
      { topic: "calls", kind: "strength", text: "What Hi-Fi found calls loud and clear, even in wind. Eight mics plus a bone-conduction sensor.", evidence: "reviewer", sources: ["whf-xm6", "sony-xm6-press"] },
      { topic: "calls", kind: "context", text: "RTINGS rates the mic only 'okay' overall, with good noise handling; very loud noise can trigger its noise gate.", evidence: "measured", sources: ["rt-xm6"] },
      { topic: "sound", kind: "strength", text: "What Hi-Fi: five stars, its favourite flagship earbuds.", evidence: "reviewer", sources: ["whf-xm6"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "sony-wf-1000xm5",
    brand: "Sony",
    name: "WF-1000XM5",
    short: "Sony XM5",
    generation: "5th-generation 1000X earbuds (previous flagship)",
    released: "Jul 2023",
    priceNote: "Widely discounted since the XM6 launch.",
    metrics: {
      price: d(299.99, "manufacturer", ["aa-xm5"]),
      anc: d(8.7, "measured", ["sg-xm5"], "medium", "Single rendering; another rendering showed 8.3 as the combined 'isolation / ANC' score."),
      batteryClaim: d(8, "manufacturer", ["sony-xm5-specs"]),
      batteryMeasured: d(8.75, "measured", ["rt-xm5"]),
      comfort: d(8.0, "reviewer", ["sg-xm5"], "medium"),
      weight: d(5.9, "manufacturer", ["sony-xm5-specs"], "high", "With M tips."),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["sony-xm5-specs"], "high", "Earbuds only; case and tips are not water resistant."),
      multipoint: d("yes", "manufacturer", ["sony-xm5-start"], "high", "Two devices, enabled in the app."),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["sony-xm5-touch"], "high", "Ambient Sound, Quick Attention, Speak-to-Chat."),
      wirelessCharging: d("yes", "manufacturer", ["sony-xm5-specs"]),
      fitAid: d("tips-only", "measured", ["rt-xm5"], "high", "Memory-foam tips, no fins."),
      controls: d("Touch: tap left bud for ambient/NC, hold for Quick Attention; volume by tap patterns", "manufacturer", ["sony-xm5-touch"], "medium"),
      heartRate: unknown(),
      ios: d("full", "manufacturer", ["sony-xm5-start"], "medium", "Sound Connect app on the App Store."),
      android: d("full", "manufacturer", ["sony-xm5-start"], "medium"),
      caseTotalHours: d(24, "manufacturer", ["sony-xm5-specs"]),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "RTINGS found them stable through tough reps at the gym even without fins.", evidence: "measured", sources: ["rt-xm5"] },
      { topic: "gym", kind: "limitation", text: "What Hi-Fi felt the fit 'could feel more secure'.", evidence: "reviewer", sources: ["whf-xm5"] },
      { topic: "calls", kind: "limitation", text: "RTINGS rates the mic mediocre; loud sustained noise overwhelms its noise handling.", evidence: "measured", sources: ["rt-xm5"] },
      { topic: "travel", kind: "strength", text: "RTINGS measured 8.75 h continuous with ANC.", evidence: "measured", sources: ["rt-xm5"] },
      { topic: "general", kind: "limitation", text: "iFixit: batteries are no longer user-replaceable with common tools.", evidence: "reviewer", sources: ["ifixit-xm5"] },
      { topic: "sound", kind: "context", text: "What Hi-Fi praised detail and timing; noted rivals have more bass. RTINGS describes a warm profile.", evidence: "reviewer", sources: ["whf-xm5", "rt-xm5"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "sony-linkbuds-fit",
    brand: "Sony",
    name: "LinkBuds Fit (WF-LS910N)",
    short: "LinkBuds Fit",
    generation: "Fit-first LinkBuds (replaced LinkBuds S)",
    released: "Nov 2024",
    metrics: {
      price: d(199.99, "manufacturer", ["soya-lbf"], "medium"),
      anc: d(7.1, "measured", ["sg-lbf"], "medium"),
      batteryClaim: d(5.5, "manufacturer", ["sony-lbf-specs"]),
      batteryMeasured: unknown("No RTINGS review found. SoundGuys measured 6 h 46 min (different lab — not plotted on this axis).", ["sg-lbf"], "measured"),
      comfort: unknown("SoundGuys lists comfort as a positive, but no score was captured.", ["sg-lbf"], "reviewer"),
      weight: d(4.9, "manufacturer", ["sony-lbf-specs"]),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["sony-lbf-specs"]),
      multipoint: d("yes", "manufacturer", ["coolblue-lbf"], "medium"),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["coolblue-lbf"], "medium", "Ambient sound mode."),
      wirelessCharging: d("no", "manufacturer", ["coolblue-lbf"], "medium", "USB-C only."),
      fitAid: d("wing-or-fin", "manufacturer", ["cr-lbf", "sony-lbf-specs"], "medium", "Soft 'Air Fitting Supporter' fins."),
      controls: d("Touch", "manufacturer", ["coolblue-lbf"], "medium"),
      heartRate: unknown(),
      ios: unknown(),
      android: unknown(),
      caseTotalHours: d(21, "manufacturer", ["coolblue-lbf"], "medium"),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "Consumer Reports found the fit stable with the Air Fitting Supporters.", evidence: "reviewer", sources: ["cr-lbf"] },
      { topic: "office", kind: "strength", text: "Galaxus called them the 'comfiest earphones ever'; light at 4.9 g.", evidence: "reviewer", sources: ["galaxus-lbf", "sony-lbf-specs"] },
      { topic: "commute", kind: "limitation", text: "A 'remarkably poor isolator' because of the shallow fit (SoundGuys); ANC score 7.1/10.", evidence: "measured", sources: ["sg-lbf", "galaxus-lbf"] },
      { topic: "travel", kind: "limitation", text: "5.5 h ANC-on claim and no wireless charging.", evidence: "manufacturer", sources: ["sony-lbf-specs", "coolblue-lbf"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "bose-qc-ultra-earbuds-2",
    brand: "Bose",
    name: "QuietComfort Ultra Earbuds (2nd Gen)",
    short: "Bose QC Ultra 2",
    generation: "2nd-generation QC Ultra Earbuds",
    released: "Jun 2025 (US Sep 2025)",
    priceNote: "Often $249 on sale through 2026.",
    metrics: {
      price: d(299, "manufacturer", ["bose-qcue2-press"]),
      anc: d(8.5, "measured", ["sg-qcue2", "sg-qcue2-wind"], "high", "About 85% average perceived-loudness reduction."),
      batteryClaim: d(6, "manufacturer", ["bose-qcue2-specs"], "high", "4 h with Immersive Audio on."),
      batteryMeasured: d(6.5, "measured", ["rt-qcue2"], "medium", "SoundGuys measured 5 h 34–37 min under its own protocol."),
      comfort: d(9.0, "reviewer", ["sg-qcue2"], "medium"),
      weight: d(7.7, "manufacturer", ["bose-qcue2-specs"], "medium", "Bose lists 0.017 lb (≈7.7 g); retailers list 7.2–8 g."),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["bose-qcue2-specs"], "high", "Earbuds; case rating not found."),
      multipoint: d("yes", "manufacturer", ["ws-qcue2", "ss-qcue2-controls"], "medium", "Up to two devices."),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["bose-qcue2-specs"], "high", "Aware mode with ActiveSense."),
      wirelessCharging: d("yes", "manufacturer", ["bose-qcue2-press"], "high", "Qi."),
      fitAid: d("stability-band", "manufacturer", ["bose-qcue2-press"], "high", "Three stability-band sizes plus three tip sizes."),
      controls: d("Touch: tap, swipe for volume, configurable press-and-hold", "manufacturer", ["ss-qcue2-controls"], "medium"),
      heartRate: unknown(),
      ios: d("full", "manufacturer", ["ss-qcue2-controls"], "low", "Bose app on iOS and Android."),
      android: d("full", "manufacturer", ["ss-qcue2-controls"], "low"),
      caseTotalHours: d(24, "manufacturer", ["bose-qcue2-specs"]),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "RTINGS rates comfort and stability great; stability bands hold the buds during workouts.", evidence: "measured", sources: ["rt-qcue2"] },
      { topic: "outdoor", kind: "limitation", text: "With ANC on, wind turns into a loud rumble — still present a year after launch (SoundGuys, Jun 2026).", evidence: "measured", sources: ["sg-qcue2-wind"] },
      { topic: "calls", kind: "context", text: "SoundGuys readers rated the mic 'okay' (mean opinion 3.11/5); What Hi-Fi praised call clarity — sources disagree.", evidence: "reviewer", sources: ["sg-qcue2-mic", "whf-qcue2"] },
      { topic: "travel", kind: "limitation", text: "RTINGS measured 6.5 h, which may not cover a long-haul flight without the case.", evidence: "measured", sources: ["rt-qcue2"] },
      { topic: "office", kind: "strength", text: "RTINGS finds them more comfortable and stable than the Sony XM6 for most people.", evidence: "measured", sources: ["rt-bose-vs-xm6"] },
      { topic: "sound", kind: "context", text: "RTINGS: warm signature with bass about +5 dB. Latency above 100 ms.", evidence: "measured", sources: ["rt-qcue2"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "galaxy-buds4-pro",
    brand: "Samsung",
    name: "Galaxy Buds4 Pro",
    short: "Galaxy Buds4 Pro",
    generation: "Buds4 Pro (replaced Buds3 Pro)",
    released: "Mar 2026",
    metrics: {
      price: d(249, "manufacturer", ["sammobile-b4p"]),
      anc: d(8.4, "measured", ["sg-b4p-review", "sg-b4p-vs-bose"], "medium", "About 84% average reduction. A conflicting 2.2 'isolation / ANC' rendering was treated as unreliable."),
      batteryClaim: d(6, "manufacturer", ["galaxus-b4p"], "medium", "Retailer reproduction of Samsung's spec."),
      batteryMeasured: unknown("RTINGS reports 'about 6 h' (listed as a con) — approximate, so not plotted. SoundGuys measured 6 h 1 min.", ["rt-b4p", "sg-b4p-vs-bose"], "measured"),
      comfort: d(8.5, "reviewer", ["sg-b4p-review"], "medium"),
      weight: d(5.1, "manufacturer", ["galaxus-b4p"], "medium"),
    },
    features: {
      ipRating: d("IP57", "manufacturer", ["galaxus-b4p"], "medium", "Samsung's IP57 covers fresh water only, not salt or pool water."),
      multipoint: d("no", "reviewer", ["sg-b4p-vs-app3"], "medium", "Reported: true multipoint missing; switching works between Galaxy devices."),
      ecosystemSwitching: d("Samsung Auto Switch between Galaxy devices", "reviewer", ["sg-b4p-vs-app3"], "medium"),
      transparency: d("yes", "reviewer", ["bgr-b4p"], "medium", "Ambient mode; Voice Detect and siren detection switch to ambient automatically."),
      wirelessCharging: d("yes", "manufacturer", ["samsung-b4"]),
      fitAid: unknown(),
      controls: d("Pinch-and-hold (customisable); head gestures for calls", "reviewer", ["bgr-b4p"], "medium"),
      heartRate: unknown(),
      ios: d("limited", "reviewer", ["sg-b4p-vs-app3"], "medium", "No iOS app: basic Bluetooth playback only."),
      android: d("full", "reviewer", ["sg-b4p-vs-app3"], "medium", "Best on Galaxy phones; Galaxy Wearable app on other Android phones."),
      caseTotalHours: d(26, "manufacturer", ["galaxus-b4p"], "medium"),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "RTINGS: comfortable, stable fit — 'a fitting fitness companion' for the gym or hiking.", evidence: "measured", sources: ["rt-b4p"] },
      { topic: "commute", kind: "strength", text: "RTINGS calls the isolation superb: chatty coworkers, construction and engines.", evidence: "measured", sources: ["rt-b4p"] },
      { topic: "calls", kind: "context", text: "RTINGS says the mic is much better in real calls than its lab score, because on-board noise suppression isn't active on the rig.", evidence: "measured", sources: ["rt-b4p", "rt-mic"] },
      { topic: "travel", kind: "limitation", text: "RTINGS: about 6 h per charge may run out on longer transcontinental flights.", evidence: "measured", sources: ["rt-b4p"] },
      { topic: "sound", kind: "context", text: "RTINGS: smooth, warm signature with slightly elevated bass.", evidence: "measured", sources: ["rt-b4p"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "nothing-ear-3",
    brand: "Nothing",
    name: "Ear (3)",
    short: "Nothing Ear (3)",
    generation: "3rd-generation Nothing Ear",
    released: "Sep 2025",
    metrics: {
      price: d(179, "manufacturer", ["pbtech-ear3"], "medium"),
      anc: d(8.2, "measured", ["sg-ear3", "sg-ear3-review"], "high", "About 82% average reduction."),
      batteryClaim: d(5.5, "manufacturer", ["tg-ear3"], "medium"),
      batteryMeasured: d(5.3, "measured", ["rt-ear3", "rt-cmf-vs-ear3"]),
      comfort: d(8.5, "reviewer", ["sg-ear3"], "medium"),
      weight: d(5.2, "manufacturer", ["91m-ear3"], "medium"),
    },
    features: {
      ipRating: d("IP54", "manufacturer", ["91m-ear3", "hc-ear3"], "medium", "Earbuds and case."),
      multipoint: d("yes", "manufacturer", ["nbc-ear3", "hc-ear3"], "medium"),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "reviewer", ["hc-ear3"], "medium", "Headphonecheck flags audible background noise in transparency mode."),
      wirelessCharging: d("yes", "manufacturer", ["nbc-ear3", "hc-ear3"], "medium", "Qi."),
      fitAid: d("tips-only", "measured", ["rt-ear3"], "high", "No stabilizers."),
      controls: d("Pressure-sensitive pinch on the stem; button on the case for Super Mic", "reviewer", ["nbc-ear3"], "medium"),
      heartRate: unknown(),
      ios: d("full", "manufacturer", ["nothing-compat", "hc-ear3"], "low", "Nothing X app; compatibility note is Nothing's general earbuds article."),
      android: d("full", "manufacturer", ["nothing-compat", "hc-ear3"], "low"),
      caseTotalHours: d(22, "manufacturer", ["tg-ear3"], "medium"),
    },
    notes: [
      { topic: "gym", kind: "limitation", text: "No stabilizers: RTINGS says they can fall out occasionally; one tester re-seated them every 15–20 minutes while running.", evidence: "measured", sources: ["rt-ear3", "mz-ear3"] },
      { topic: "office", kind: "strength", text: "Tom's Guide found them very comfortable for all-day wear.", evidence: "reviewer", sources: ["tg-ear3"] },
      { topic: "calls", kind: "context", text: "RTINGS praises the mic's background-noise rejection; SoundGuys calls it 'muffled' and the case Super Mic underwhelming.", evidence: "reviewer", sources: ["rt-ear3", "sg-ear3-review"] },
      { topic: "travel", kind: "limitation", text: "Short battery: RTINGS measured 5.3 h; the metal case weighs 71.4 g.", evidence: "measured", sources: ["rt-ear3", "91m-ear3"] },
      { topic: "sound", kind: "context", text: "Tom's Guide: powerful bass, occasionally harsh treble.", evidence: "reviewer", sources: ["tg-ear3"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "nothing-ear-3a",
    brand: "Nothing",
    name: "Ear (3a)",
    short: "Nothing Ear (3a)",
    generation: "3rd-generation Ear (a) line (replaced Ear (a))",
    released: "Jul 2026",
    metrics: {
      price: d(99, "manufacturer", ["tc-ear3a"]),
      anc: d(8.1, "measured", ["sg-ear3a", "sg-ear3a-vs-a"], "medium", "SoundGuys: 'nearly 81%' average reduction."),
      batteryClaim: d(6, "manufacturer", ["tc-ear3a", "tru-ear3a"]),
      batteryMeasured: unknown("RTINGS: 'just over six hours' — approximate, so not plotted.", ["rt-ear3a"], "measured"),
      comfort: d(8.5, "reviewer", ["sg-ear3a"], "medium"),
      weight: d(4.53, "manufacturer", ["tc-ear3a"], "medium"),
    },
    features: {
      ipRating: d("IP54", "manufacturer", ["tru-ear3a"], "medium", "Earbuds and case."),
      multipoint: d("yes", "manufacturer", ["tc-ear3a"], "medium"),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["tc-ear3a"], "medium"),
      wirelessCharging: d("no", "reviewer", ["tr-ear3a"], "medium", "USB-C only."),
      fitAid: unknown(),
      controls: unknown(),
      heartRate: unknown(),
      ios: d("full", "manufacturer", ["nothing-compat"], "medium", "Nothing X app; iOS 13+."),
      android: d("full", "manufacturer", ["nothing-compat"], "medium", "Android 8.0+."),
      caseTotalHours: d(25, "manufacturer", ["tc-ear3a"]),
    },
    notes: [
      { topic: "commute", kind: "strength", text: "RTINGS: great ANC that handles everything from bus rumble to fan whine.", evidence: "measured", sources: ["rt-ear3a"] },
      { topic: "calls", kind: "limitation", text: "RTINGS: very good noise handling, but voices sound thin and nasal — better for occasional calls than a day of meetings.", evidence: "measured", sources: ["rt-ear3a"] },
      { topic: "office", kind: "context", text: "On-board call recording (32 MB) — check consent rules before using it.", evidence: "manufacturer", sources: ["tc-ear3a"] },
      { topic: "travel", kind: "limitation", text: "No wireless charging.", evidence: "reviewer", sources: ["tr-ear3a"] },
      { topic: "sound", kind: "context", text: "SoundGuys: the stock tuning needs a heavy hand with EQ to match typical preferences.", evidence: "reviewer", sources: ["sg-ear3a"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cmf-buds-pro-2",
    brand: "CMF",
    name: "Buds Pro 2",
    short: "CMF Buds Pro 2",
    generation: "2nd-generation CMF Buds Pro (Nothing sub-brand)",
    released: "Jul 2024",
    metrics: {
      price: d(59, "manufacturer", ["pa-cmf"], "medium", "Tom's Guide cites $69."),
      anc: d(8.1, "measured", ["sg-cmf"], "high", "About 81% average reduction."),
      batteryClaim: d(6.5, "manufacturer", ["pa-cmf"]),
      batteryMeasured: d(6.5, "measured", ["rt-cmf-vs-ear3"]),
      comfort: d(8.0, "reviewer", ["sg-cmf"], "medium"),
      weight: d(4.9, "manufacturer", ["pa-cmf"]),
    },
    features: {
      ipRating: d("IP55", "manufacturer", ["nothing-cmf"], "high", "Whether the case is also rated isn't stated."),
      multipoint: d("yes", "manufacturer", ["pa-cmf"], "medium"),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["pa-cmf"], "medium"),
      wirelessCharging: unknown("Not confirmed in our sources; USB-C charging is documented."),
      fitAid: d("tips-only", "measured", ["rt-cmf"], "medium", "No stabilizers."),
      controls: d("Touch on the buds plus a Smart Dial on the case", "manufacturer", ["nothing-cmf"]),
      heartRate: unknown(),
      ios: unknown(),
      android: unknown(),
      caseTotalHours: d(26, "manufacturer", ["pa-cmf"]),
    },
    notes: [
      { topic: "gym", kind: "context", text: "Reviewers split: TechRadar lists poor in-ear grip; RTINGS still rates them very good for sports. IP55 is the highest rating among non-IP57 models here.", evidence: "reviewer", sources: ["tr-cmf", "rt-cmf", "nothing-cmf"] },
      { topic: "commute", kind: "strength", text: "SoundGuys: strong on low-frequency noise (about 81% overall), weaker on high-pitched noise like screeching buses.", evidence: "measured", sources: ["sg-cmf"] },
      { topic: "general", kind: "context", text: "Tom's Guide gave an Editor's Choice; TechRadar was negative — the widest verdict spread in this set.", evidence: "reviewer", sources: ["tg-cmf", "tr-cmf"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "sennheiser-mtw5",
    brand: "Sennheiser",
    name: "Momentum True Wireless 5",
    short: "Sennheiser MTW5",
    generation: "5th-generation Momentum True Wireless (replaced MTW4)",
    released: "Sep 2026",
    metrics: {
      price: d(299.95, "manufacturer", ["senn-mtw5-news", "ecoustics-mtw5"]),
      anc: unknown("The SoundGuys ANC rendering was mixed up with the over-ear Momentum 5 Wireless — not used.", ["sg-mtw5"], "measured"),
      batteryClaim: d(6, "manufacturer", ["thomann-mtw5"], "low", "Retailer listing; another retailer lists 4 h — conflicting."),
      batteryMeasured: d(6.5, "measured", ["rt-mtw5"], "medium"),
      comfort: d(8.5, "reviewer", ["sg-mtw5"], "medium"),
      weight: d(7, "manufacturer", ["thomann-mtw5"], "low", "Retailer listing."),
    },
    features: {
      ipRating: d("IP54", "manufacturer", ["thomann-mtw5", "fillion-mtw5"], "medium"),
      multipoint: unknown("Not documented in our sources."),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "manufacturer", ["fillion-mtw5"], "medium"),
      wirelessCharging: unknown(),
      fitAid: d("tips-only", "manufacturer", ["ecoustics-mtw5", "rt-mtw5"], "medium", "Fins dropped from this generation."),
      controls: unknown(),
      heartRate: unknown(),
      ios: unknown(),
      android: unknown(),
      caseTotalHours: unknown("Retailer figures conflict."),
    },
    notes: [
      { topic: "gym", kind: "strength", text: "RTINGS: highly stable and very comfortable despite losing the fins.", evidence: "measured", sources: ["rt-mtw5"] },
      { topic: "general", kind: "strength", text: "User-replaceable batteries in the buds and case.", evidence: "manufacturer", sources: ["senn-mtw5-news"] },
      { topic: "commute", kind: "context", text: "RTINGS: fantastic ANC, though 'not quite on par with the very best'.", evidence: "measured", sources: ["rt-mtw5"] },
      { topic: "calls", kind: "context", text: "Four mics per bud including a bone-conduction sensor (manufacturer spec; not lab-verified here).", evidence: "manufacturer", sources: ["fillion-mtw5"] },
      { topic: "sound", kind: "strength", text: "TechRadar: their sound alone makes them 'the buds to beat'.", evidence: "reviewer", sources: ["tr-mtw5"] },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "technics-eah-az100",
    brand: "Technics",
    name: "EAH-AZ100",
    short: "Technics AZ100",
    generation: "Flagship (successor to EAH-AZ80)",
    released: "Jan 2025",
    metrics: {
      price: d(299, "manufacturer", ["cn-az100", "rn-az100"], "medium"),
      anc: d(8.3, "measured", ["sg-az100"], "medium", "Single rendering; a separate 'isolation / ANC' composite read 6.3."),
      batteryClaim: d(10, "manufacturer", ["jb-az100", "cn-az100"], "medium"),
      batteryMeasured: d(12.2, "measured", ["rt-az100-vs-app3"], "medium"),
      comfort: d(8.0, "reviewer", ["sg-az100"], "medium"),
      weight: d(5.9, "manufacturer", ["jb-az100"], "medium"),
    },
    features: {
      ipRating: d("IPX4", "manufacturer", ["jb-az100"], "medium"),
      multipoint: d("yes", "manufacturer", ["jb-az100"], "medium", "Up to three devices."),
      ecosystemSwitching: unknown(),
      transparency: d("yes", "reviewer", ["sg-az100"], "medium", "Ambient / passthrough mode."),
      wirelessCharging: d("yes", "manufacturer", ["jb-az100", "sg-az100"], "medium"),
      fitAid: unknown(),
      controls: unknown(),
      heartRate: unknown(),
      ios: unknown(),
      android: unknown(),
      caseTotalHours: unknown("Sources disagree on whether 28 h is the total or additional."),
    },
    notes: [
      { topic: "travel", kind: "strength", text: "Longest measured battery here: RTINGS 12.2 h continuous; SoundGuys about 12 h.", evidence: "measured", sources: ["rt-az100-vs-app3", "sg-az100"] },
      { topic: "gym", kind: "strength", text: "RTINGS rates them great for sports and fitness, and more comfortable and stable than AirPods Pro 3 for most people.", evidence: "measured", sources: ["rt-az100-vs-app3"] },
      { topic: "office", kind: "strength", text: "Multipoint with up to three devices.", evidence: "manufacturer", sources: ["jb-az100"] },
      { topic: "general", kind: "limitation", text: "SoundGuys: the size isn't for everyone, though they nestle comfortably in most ears for a couple of hours.", evidence: "reviewer", sources: ["sg-az100"] },
      { topic: "sound", kind: "context", text: "What Hi-Fi gave five stars; SoundGuys listed 'odd sound' as a con — reviewers disagree.", evidence: "reviewer", sources: ["whf-az100", "sg-az100"] },
    ],
  },
];

export const PRODUCT_BY_ID: Record<string, Product> = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));
