import type { Capability } from "./types";

/**
 * The eleven capability layers of a production-grade harness (PRD §6).
 * Ordering is deliberate: perception → action → coordination → control → proof.
 */
export const CAPABILITIES: Capability[] = [
  {
    id: "context",
    name: "Context",
    icon: "ScanSearch",
    question: "What does the model need to know right now?",
    essence: "Assembling the smallest set of high-signal tokens that lets the model act well.",
    depth: {
      exec: "Models don't know your business; the harness decides what they see. Two teams with the same model and different context assembly get different answers — and different bills. Context is where enterprise knowledge becomes model behavior.",
      architect: "Context engineering is a pipeline: system instructions, user/session context, retrieval over enterprise data, dynamic assembly per step, compression when the window fills, caching of stable prefixes, and prioritization when candidates exceed budget. Anthropic frames this as managing the model's 'attention budget' — more context is not more accuracy.",
      developer: "In practice: retrieval (vector, keyword, or agentic search over files/APIs), prompt-cache-friendly message ordering (stable prefix first), compaction/summarization triggers at window thresholds, and just-in-time context (letting the agent fetch what it needs via tools rather than front-loading). Cache hit rate often matters more than raw token count.",
    },
    mechanisms: [
      "System instructions",
      "Retrieval / RAG",
      "Agentic search",
      "Dynamic assembly",
      "Compaction",
      "Prompt caching",
      "Just-in-time fetching",
    ],
    withoutIt: "The model guesses. Hallucinated policy, stale data, bloated prompts — and token spend that grows with every feature.",
    hue: 217,
  },
  {
    id: "memory",
    name: "Memory",
    icon: "Database",
    question: "What should persist beyond this conversation?",
    essence: "Deciding what the system remembers — per session, per user, per task, per enterprise.",
    depth: {
      exec: "Without memory, every interaction starts from zero and your agents never get smarter about your business. With unmanaged memory, they accumulate stale or sensitive facts. Memory policy is a governance decision, not a feature toggle.",
      architect: "Separate the stores: session memory (working state), user memory (preferences, history), task memory (progress on long work), and enterprise memory (shared knowledge). Episodic ('what happened') and semantic ('what is true') memory age differently and need different retention and access rules.",
      developer: "Implementations range from checked-in instruction files (CLAUDE.md / AGENTS.md), to managed stores (Agent Engine Memory Bank, AgentCore Memory), to dedicated memory frameworks (Letta/MemGPT lineage). Key design choices: write policy (what gets saved), recall policy (what gets injected when), and expiry.",
    },
    mechanisms: [
      "Session state",
      "User memory",
      "Task memory",
      "Enterprise memory",
      "Instruction files",
      "Managed memory banks",
    ],
    withoutIt: "Groundhog Day agents: users repeat themselves, long tasks can't survive a restart, and nothing learned ever compounds.",
    hue: 262,
  },
  {
    id: "tools",
    name: "Tools",
    icon: "Wrench",
    question: "What can the model actually do?",
    essence: "The verbs: APIs, databases, browsers, shells, and enterprise systems the agent may call.",
    depth: {
      exec: "Tools are where agents stop being chatbots and start doing work — and where risk concentrates. The tool surface defines your blast radius: an agent is exactly as dangerous as the tools it holds.",
      architect: "Design questions: how tools are described (schemas consume context), how they're discovered (static registry vs. MCP servers), how results are shaped (raw dumps poison context), and whether the agent calls tools directly or writes code against them. Anthropic showed code-execution-over-MCP cutting tool overhead from ~150k to ~2k tokens in one example (Nov 2025).",
      developer: "MCP is now the cross-vendor default for tool connectivity (Linux Foundation-governed since Dec 2025). Watch: tool-result size limits, parallel tool calls, sandboxed execution for shell/code tools, idempotency for retries, and per-tool authorization scopes.",
    },
    mechanisms: [
      "Function calling",
      "MCP servers",
      "Code execution",
      "Browser control",
      "Enterprise APIs",
      "Database access",
      "Search",
    ],
    withoutIt: "An eloquent adviser that can't book, file, fix, query, or ship anything. All insight, no work.",
    hue: 30,
  },
  {
    id: "orchestration",
    name: "Orchestration",
    icon: "GitBranch",
    question: "How does multi-step work actually happen?",
    essence: "Planning, routing, retries, branching, parallelism, subagents — the control flow of work.",
    depth: {
      exec: "Real tasks take many steps, and step-to-step coordination is where agents either compound value or compound errors. Orchestration choice decides whether ten agents are a workforce or a mob.",
      architect: "The central trade-off: deterministic workflows (predictable, auditable, rigid) versus model-driven agency (flexible, adaptive, harder to bound). Production systems blend both — workflow rails for the business process, agentic freedom inside each step. Subagents isolate context per concern; routers pick models per step.",
      developer: "Patterns: planner/executor splits, subagent fan-out with context isolation, model routing (cheap model for triage, frontier for hard steps), retry-with-feedback loops, and parallel exploration with a judge. Frameworks (LangGraph, ADK, Agent Framework) encode these as graphs; harnesses like Claude Code encode them as built-in behaviors.",
    },
    mechanisms: [
      "Planning",
      "Workflow graphs",
      "Subagents",
      "Model routing",
      "Retries",
      "Parallel execution",
      "Multi-agent teams",
    ],
    withoutIt: "Single-shot prompting with extra steps: no decomposition, no recovery mid-task, no way to use the right model per step.",
    hue: 199,
  },
  {
    id: "state",
    name: "State",
    icon: "ListChecks",
    question: "Where is the system within the task?",
    essence: "Task state, checkpoints, resumability — so long-running work survives interruption.",
    depth: {
      exec: "Enterprise processes run for hours, days, or weeks. An agent that loses its place when a session ends can't hold a real job. Durable state is the difference between a demo and an employee.",
      architect: "Distinguish conversation state (messages), task state (progress against a goal), and workflow state (where in a defined process). Long-running agents need checkpointing, resumability after failure, and human-approval pauses that can last days without losing position.",
      developer: "Mechanisms: session persistence, checkpoint/rewind (Claude Code checkpoints), durable-execution engines (Temporal-style), state stores in managed runtimes (Agent Engine sessions, AgentCore), and initializer/worker harness patterns for multi-session work (Anthropic, Nov 2025).",
    },
    mechanisms: [
      "Session persistence",
      "Checkpoints",
      "Resumability",
      "Durable execution",
      "Long-running processes",
      "Approval pauses",
    ],
    withoutIt: "Every interruption is a restart. Long tasks silently lose work, and 'try again' becomes your recovery strategy.",
    hue: 172,
  },
  {
    id: "identity",
    name: "Identity & Permissions",
    icon: "Fingerprint",
    question: "Who is the agent, and what may it do?",
    essence: "Agent identity, delegated authority, least privilege, and transactional limits.",
    depth: {
      exec: "When an agent acts, whose authority is it using? If you can't answer that per action, you can't pass an audit. Agent identity is becoming the control plane of enterprise AI — and the least mature layer at most companies.",
      architect: "Agents need their own identities (not shared service accounts), scoped delegation from users ('acting for Alice, limited to X'), least-privilege tool grants, and hard transactional limits (amounts, systems, data classes). Permission checks belong in the harness and the tool gateway — not in the prompt.",
      developer: "Building blocks: per-agent service identities (cloud IAM), OAuth token exchange for delegated access, tool-level authorization (gateway policies, e.g. Apigee-style), approval-required tool tiers, and permission modes (read-only → workspace-write → full) as coding harnesses like Codex and Claude Code implement.",
    },
    mechanisms: [
      "Agent identity",
      "Delegated auth",
      "Least privilege",
      "Tool authorization",
      "Permission modes",
      "Transaction limits",
    ],
    withoutIt: "Agents act as over-privileged shared accounts. One prompt injection away from a very bad security review.",
    hue: 0,
  },
  {
    id: "evaluation",
    name: "Evaluation & Verification",
    icon: "BadgeCheck",
    question: "How do we know the output is good?",
    essence: "Deterministic checks, tests, judges, and grounding — proof, not vibes.",
    depth: {
      exec: "The teams shipping agents successfully are the ones that can measure them. If you can't objectively score a model-harness pair before production, every model upgrade is a leap of faith.",
      architect: "Two loops: inner verification (the harness checks each step — tests pass, output parses, claims grounded) and outer evaluation (regression suites over golden tasks, scored per model-harness configuration). Coding agents win precisely because compilers and tests give the harness a free inner loop; other domains must build one.",
      developer: "Tooling: deterministic validators, unit/integration tests as agent feedback, LLM-as-judge with rubrics, grounding/citation checks, trajectory evals (did it take a sane path?), and eval services (Vertex gen-AI evaluation, LangSmith, Harness-Bench-style task suites). Evals belong in CI, gating agent changes like code changes.",
    },
    mechanisms: [
      "Deterministic checks",
      "Tests as feedback",
      "LLM-as-judge",
      "Grounding checks",
      "Trajectory evals",
      "Golden-task suites",
    ],
    withoutIt: "You learn about failures from users. Model upgrades and prompt tweaks ship on hope; quality drifts invisibly.",
    hue: 145,
  },
  {
    id: "guardrails",
    name: "Guardrails",
    icon: "ShieldAlert",
    question: "What must the system never do?",
    essence: "Safety filters, injection defense, data controls, and hard action constraints.",
    depth: {
      exec: "Guardrails are the difference between an incident and a headline. The critical shift: constraints enforced by the system, not requested in the prompt. 'Please don't' is not a control.",
      architect: "Layer them: input screening (prompt-injection and jailbreak detection), data controls (DLP on what enters and leaves context), output policy (content, claims, formats), and action constraints (which tools, which limits, which environments). Treat every tool result and retrieved document as untrusted input.",
      developer: "Mechanisms: model-level safety settings, dedicated screening services (Model Armor-class), sandboxed execution (OS-level like Seatbelt/Landlock in Codex, containers in cloud agents), allowlisted network egress, and policy engines at the tool gateway. Injection defense is an arms race — design for containment, not just detection.",
    },
    mechanisms: [
      "Injection screening",
      "DLP / data controls",
      "Output policy",
      "Action constraints",
      "Sandboxing",
      "Egress control",
    ],
    withoutIt: "Your agent does what any sufficiently creative input tells it to — with whatever permissions you gave it.",
    hue: 350,
  },
  {
    id: "observability",
    name: "Observability",
    icon: "Telescope",
    question: "What actually happened, and why?",
    essence: "Traces of every model call, tool call, token, and decision — reconstructable after the fact.",
    depth: {
      exec: "When an agent does something surprising, 'we're not sure what it did' is not an acceptable answer — to your customers, your auditors, or your board. Observability is what makes agents governable at all.",
      architect: "Trace the trajectory, not just the calls: prompts and context as-assembled, tool invocations with inputs/outputs, token and latency per step, routing decisions, and failure classification. Aggregate to fleet level: cost per task, success rates, failure modes by type — per model-harness pair.",
      developer: "OpenTelemetry-based agent tracing is converging as the standard (GenAI semantic conventions); platforms ship it natively (Agent Engine, AgentCore, LangSmith, Azure AI Foundry). Log context assembly, not just the final prompt — most bugs live in what the model was shown.",
    },
    mechanisms: [
      "Trajectory traces",
      "Tool-call logs",
      "Token accounting",
      "Latency breakdown",
      "Failure taxonomy",
      "OpenTelemetry GenAI",
    ],
    withoutIt: "Debugging by anecdote. No audit trail, no cost attribution, no way to prove what the agent did or didn't do.",
    hue: 282,
  },
  {
    id: "recovery",
    name: "Recovery",
    icon: "LifeBuoy",
    question: "What happens when something fails?",
    essence: "Retries, fallbacks, rollback, escalation — failure as a designed path, not an exception.",
    depth: {
      exec: "Agents fail constantly in small ways; mature systems make those failures invisible and cheap. The question isn't whether your agent fails — it's whether failure costs a retry or a rollback of production data.",
      architect: "Design the failure ladder: automatic retry (with changed strategy, not blind repetition) → fallback model or tool → checkpoint restore → human escalation with full context. Separate recoverable steps (idempotent, sandboxed) from irreversible ones (transactions), and gate the latter with approvals.",
      developer: "Mechanics: bounded retries with error feedback in context, model fallback chains, checkpoint/rewind, compensating transactions for side effects, and escalation payloads that include the trajectory so humans don't start from zero. Long-running harnesses need clean-slate restarts that preserve durable state.",
    },
    mechanisms: [
      "Retry with feedback",
      "Fallback models",
      "Checkpoint restore",
      "Rollback / compensation",
      "Human escalation",
    ],
    withoutIt: "Every failure is terminal or, worse, silent. Half-finished side effects accumulate in production systems.",
    hue: 22,
  },
  {
    id: "economics",
    name: "Economics",
    icon: "CircleDollarSign",
    question: "What does a successful task actually cost?",
    essence: "Tokens, calls, caching, routing, retries — engineered as a first-class budget.",
    depth: {
      exec: "The cheapest model per token is routinely not the cheapest per completed task. Harness efficiency — context discipline, caching, routing, fewer retries — moves cost more than model list price. Buy outcomes, not tokens.",
      architect: "Instrument cost per successful task: (tokens × price, per model, across all turns and retries) ÷ tasks completed acceptably. Research in 2026 measured up to 40× differences in tokens per solved task across harnesses running the same model. Cache-aware accounting matters: a harness sending 200k tokens at a 95% cache-hit rate beats one sending 20k at 25%.",
      developer: "Levers: prompt-cache-friendly context layout, compaction thresholds, model routing per step, tool-result truncation, code-execution over raw tool calls, parallelism caps, and per-task token budgets enforced by the harness. Track spend per trajectory, not per API key.",
    },
    mechanisms: [
      "Cost per successful task",
      "Prompt caching",
      "Model routing",
      "Context budgets",
      "Compaction",
      "Retry accounting",
    ],
    withoutIt: "Costs scale with traffic and entropy. Finance sees a token bill; nobody can say what a completed task costs.",
    hue: 122,
  },
];

export const capById = (id: string): Capability => {
  const c = CAPABILITIES.find((x) => x.id === id);
  if (!c) throw new Error(`unknown capability: ${id}`);
  return c;
};
