import type { Workload } from "./types";

/**
 * Workload → capability-weight matrix (PRD §10, Deliverable 4).
 * Weights are analyst judgment (1 = background, 5 = decisive), designed to show
 * that "which harness" is a workload question before it is a vendor question.
 */
export const WORKLOADS: Workload[] = [
  {
    id: "coding",
    name: "Coding",
    icon: "Code2",
    tagline: "The clearest demonstration of harness differentiation in the market.",
    traits: [
      "Repository context",
      "Shell access",
      "Tests as ground truth",
      "Long-running tasks",
      "Verification loops",
    ],
    weights: {
      context: 5,
      memory: 3,
      tools: 5,
      orchestration: 4,
      state: 4,
      identity: 3,
      evaluation: 5,
      guardrails: 3,
      observability: 3,
      recovery: 4,
      economics: 4,
    },
    rationale:
      "Coding won first because the harness gets verification for free: compilers, tests and linters give every step a pass/fail signal. Repo-scale context assembly and safe shell/tool access do the rest — which is why the same model scores differently in different coding harnesses.",
    exemplars: ["Claude Code", "Codex", "Antigravity", "Cursor", "OpenHands", "Copilot coding agent"],
  },
  {
    id: "search",
    name: "Enterprise Search",
    icon: "FileSearch",
    tagline: "Grounded answers over governed knowledge — permissions are the product.",
    traits: ["Retrieval", "Grounding", "Citations", "Identity-aware ACLs", "Freshness"],
    weights: {
      context: 5,
      memory: 2,
      tools: 3,
      orchestration: 2,
      state: 1,
      identity: 5,
      evaluation: 4,
      guardrails: 4,
      observability: 3,
      recovery: 2,
      economics: 3,
    },
    rationale:
      "The hard part isn't answering — it's answering only from documents this user may see, with citations that survive audit. Context (retrieval quality) and identity (ACL-aware results) dominate; orchestration barely matters.",
    exemplars: ["Gemini Enterprise", "Vertex AI Search", "Glean-class platforms", "M365 Copilot"],
  },
  {
    id: "service",
    name: "Customer Service",
    icon: "Headset",
    tagline: "Conversation plus consequences: CRM writes, refunds, escalation.",
    traits: ["CRM access", "Conversational state", "Workflow execution", "Escalation paths", "Brand guardrails"],
    weights: {
      context: 4,
      memory: 4,
      tools: 5,
      orchestration: 4,
      state: 4,
      identity: 4,
      evaluation: 3,
      guardrails: 5,
      observability: 4,
      recovery: 5,
      economics: 4,
    },
    rationale:
      "Every turn can touch money and reputation. Guardrails and recovery outrank raw intelligence: a wrong refund, an off-policy promise, or a dead-end with no human handoff costs more than a slightly worse answer ever would.",
    exemplars: ["Salesforce Agentforce", "Copilot Studio", "Gemini Enterprise agents", "Custom on ADK/LangGraph"],
  },
  {
    id: "research",
    name: "Research",
    icon: "Microscope",
    tagline: "Long-horizon exploration with source verification.",
    traits: ["Browsing", "Document analysis", "Planning", "Iterative exploration", "Source verification"],
    weights: {
      context: 5,
      memory: 3,
      tools: 4,
      orchestration: 5,
      state: 3,
      identity: 2,
      evaluation: 4,
      guardrails: 2,
      observability: 3,
      recovery: 3,
      economics: 3,
    },
    rationale:
      "Deep research is an orchestration problem: decompose, fan out, read, cross-check, synthesize. Context management decides whether hour three still remembers hour one; verification separates research from confident summarizing.",
    exemplars: ["Deep-research modes (Gemini, ChatGPT, Claude)", "Custom multi-agent on ADK/LangGraph"],
  },
  {
    id: "data",
    name: "Data Analysis",
    icon: "BarChart3",
    tagline: "Code execution over governed data, with answers you can check.",
    traits: ["Code execution", "Data access", "Visualization", "Validation", "Semantic layer"],
    weights: {
      context: 4,
      memory: 2,
      tools: 5,
      orchestration: 3,
      state: 2,
      identity: 4,
      evaluation: 5,
      guardrails: 3,
      observability: 3,
      recovery: 3,
      economics: 3,
    },
    rationale:
      "Like coding, analysis has a free verifier — the query either runs or it doesn't, and results can be sanity-checked. Tool quality (SQL, notebooks, semantic layers) and evaluation (is that number right?) carry the workload; identity governs who may query what.",
    exemplars: ["Conversational Analytics (BigQuery/Looker)", "Code-interpreter harnesses", "Custom data agents"],
  },
  {
    id: "process",
    name: "Business Process",
    icon: "Workflow",
    tagline: "Transactions, approvals, and audits over days or weeks.",
    traits: ["Enterprise APIs", "Transactions", "Approvals", "Long-running state", "Auditability"],
    weights: {
      context: 3,
      memory: 3,
      tools: 5,
      orchestration: 5,
      state: 5,
      identity: 5,
      evaluation: 3,
      guardrails: 5,
      observability: 5,
      recovery: 5,
      economics: 3,
    },
    rationale:
      "This is the maximal-harness workload: nearly every layer at full weight. Durable state, delegated identity, hard action constraints, complete audit trails and designed recovery matter more than model brilliance — the model is the smallest architectural risk on this list.",
    exemplars: ["AgentCore + Policy", "Foundry hosted agents", "Agent Engine + Apigee", "Temporal-backed custom"],
  },
  {
    id: "productivity",
    name: "Personal Productivity",
    icon: "CalendarClock",
    tagline: "Email, calendar, documents — an assistant that knows you.",
    traits: ["User context", "Email/calendar tools", "Persistent memory", "Cross-app actions", "Privacy boundaries"],
    weights: {
      context: 4,
      memory: 5,
      tools: 4,
      orchestration: 2,
      state: 2,
      identity: 4,
      evaluation: 2,
      guardrails: 4,
      observability: 2,
      recovery: 2,
      economics: 3,
    },
    rationale:
      "Memory is the moat: an assistant that forgets your preferences weekly is a toy. User-scoped identity and privacy guardrails are non-negotiable because the context is personal by definition.",
    exemplars: ["Workspace Studio", "M365 Copilot", "ChatGPT Workspace Agents", "Claude Cowork-class assistants"],
  },
];
