import type { Model, NewsItem } from "./types";

/**
 * MODEL CATALOG — the hand-verified snapshot the site renders from.
 *
 * Prices are USD per 1M tokens at the standard (lowest) context tier,
 * first-party API unless `thirdPartyPricing` is set. Every entry carries
 * sources, a lastVerified date and a verification level:
 *   official  — official page fetched directly on lastVerified
 *   indexed   — official page read via search-index extracts and cross-checked
 *               against ≥2 independent trackers (official domain was
 *               egress-blocked from the research environment)
 *   secondary — third-party sources only
 * Facts that could not be confirmed are listed in `unverified` and rendered
 * as such. Nothing here is estimated.
 *
 * To update: edit the entry, bump lastVerified, add a SEED_NEWS item if the
 * price changed. The daily cron overlays confirmed changes without touching
 * this file (see refresh.ts).
 */

export const CATALOG_VERSION = "2026.10.06-1";
export const CATALOG_DATE = "2026-10-06";

const V = "2026-10-06";

export const CATALOG: Model[] = [
  // ───────────────────────── Anthropic (official pages fetched) ─────────────────────────
  {
    id: "claude-fable-5-1",
    apiId: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    provider: "anthropic",
    family: "Claude 5",
    series: { name: "Fable", rung: "flagship" },
    released: "2026-09-01",
    status: "ga",
    servedBy: "Anthropic API",
    pricing: {
      input: 10,
      output: 50,
      cachedInput: 0.25,
      cacheWrite: 12.5,
      cacheNote: "5-min cache write 1.25×, 1-hour write 2×; cache reads 0.025× (lowest multiplier in the lineup).",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Full 1M context at standard pricing — no >200K tier.", "Thinking always on; depth via effort. 30-day data retention required."],
    },
    contextK: 1000,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "always", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "aa-index": { score: 53, note: "v4.3 at max effort; tied with GPT-6 Astra" },
      lmarena: { score: 1501, note: "Oct 2026 tracker snapshot" },
      gpqa: { score: 94.6, note: "Tracker-listed; reporter unstated" },
      "mmlu-pro": { score: 89.3, note: "Tracker-listed" },
    },
    tier: "frontier",
    bestFor: ["research", "coding", "agents"],
    tradeoff: "Top-end reasoning and long-horizon agent work; 5× Opus 5.5 output price and no fast mode.",
    sources: [
      { label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
      { label: "Fable 5.1 overview", url: "https://platform.claude.com/docs/en/models/fable-5-1/overview" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/claude-fable-5-1" },
    ],
    lastVerified: V,
    verification: "official",
    unverified: ["Anthropic reports SWE-bench Pro (81.2%) rather than Verified; tracker 'Verified' figures for this model are carry-overs from Fable 5 and are excluded."],
  },
  {
    id: "claude-opus-5-5",
    apiId: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    provider: "anthropic",
    family: "Claude 5",
    series: { name: "Opus", rung: "flagship" },
    released: "2026-09-22",
    status: "ga",
    servedBy: "Anthropic API",
    pricing: {
      input: 4,
      output: 20,
      cachedInput: 0.2,
      cacheWrite: 5,
      cacheNote: "Cache reads 0.05× input; 5-min write 1.25×, 1-hour write 2×.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Fast mode (research preview, Claude API only): $8 / $40.", "Priced 20% below its predecessor Opus 5 ($5 / $25)."],
    },
    contextK: 1000,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "always", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "aa-index": { score: 58, note: "v4.3 at max effort — highest measured at snapshot" },
      lmarena: { score: 1509, note: "Oct 2026 tracker snapshot (#1 text)" },
    },
    tier: "frontier",
    bestFor: ["coding", "agents", "research"],
    tradeoff: "Anthropic's recommended default: frontier capability at a mid-frontier price; thinking cannot be disabled (lower effort instead).",
    sources: [
      { label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
      { label: "Opus 5.5 overview", url: "https://platform.claude.com/docs/en/models/opus-5-5/overview" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/claude-sonnet-5-5" },
    ],
    lastVerified: V,
    verification: "official",
    unverified: ["GPQA / SWE-bench Verified not reported by Anthropic for this model (SWE-bench Pro 89.9% reported instead)."],
  },
  {
    id: "claude-sonnet-5-5",
    apiId: "claude-sonnet-5-5",
    name: "Claude Sonnet 5.5",
    provider: "anthropic",
    family: "Claude 5",
    series: { name: "Sonnet", rung: "mid" },
    released: "2026-09-28",
    status: "ga",
    servedBy: "Anthropic API",
    pricing: {
      input: 2,
      output: 10,
      cachedInput: 0.2,
      cacheWrite: 2.5,
      cacheNote: "Cache reads 0.1× input; 5-min write 1.25×, 1-hour write 2×.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Price-neutral successor to Sonnet 5 (whose $2 / $10 was made permanent in Aug 2026)."],
    },
    contextK: 1000,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "always", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "aa-index": { score: 56 },
    },
    tier: "balanced",
    bestFor: ["coding", "agents", "chat"],
    tradeoff: "Everyday coding/agent workhorse at 1/5 of Fable's price; thinking only reducible to a between-tools mode.",
    sources: [
      { label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
      { label: "Sonnet 5.5 overview", url: "https://platform.claude.com/docs/en/models/sonnet-5-5/overview" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/claude-sonnet-5-5" },
    ],
    lastVerified: V,
    verification: "official",
    unverified: ["GPQA / SWE-bench Verified not reported by Anthropic for this model (SWE-bench Pro 81.3% reported instead)."],
  },
  {
    id: "claude-haiku-4-5",
    apiId: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    family: "Claude 4",
    series: { name: "Haiku", rung: "light" },
    released: "2025-10-15",
    status: "ga",
    servedBy: "Anthropic API",
    pricing: {
      input: 1,
      output: 5,
      cachedInput: 0.1,
      cacheWrite: 1.25,
      cacheNote: "Cache reads 0.1× input; 5-min write 1.25×, 1-hour write 2×.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Pinned id claude-haiku-4-5-20251001; manual extended thinking (budget_tokens), no effort parameter."],
    },
    contextK: 200,
    maxOutputK: 64,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "swe-verified": { score: 73, selfReported: true, note: "Anthropic scaffold, Oct 2025" },
    },
    tier: "economy",
    bestFor: ["chat", "bulk", "multimodal"],
    tradeoff: "Cheapest Claude and the subagent/bulk model; 200K context and a 2025-generation capability ceiling.",
    sources: [
      { label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
      { label: "Haiku 4.5 overview", url: "https://platform.claude.com/docs/en/models/haiku-4-5/overview" },
    ],
    lastVerified: V,
    verification: "official",
  },
  {
    id: "claude-opus-5",
    apiId: "claude-opus-5",
    name: "Claude Opus 5",
    provider: "anthropic",
    family: "Claude 5",
    series: { name: "Opus", rung: "flagship" },
    released: "2026-07-24",
    status: "legacy",
    servedBy: "Anthropic API",
    pricing: {
      input: 5,
      output: 25,
      cachedInput: 0.5,
      cacheWrite: 6.25,
      cacheNote: "Cache reads 0.1×.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Superseded by Opus 5.5 at a lower price; still active (retirement not before 2027-07-24)."],
    },
    contextK: 1000,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "always", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "aa-index": { score: 51, note: "v4.3 at max effort" },
      gpqa: { score: 93.2 },
      "mmlu-pro": { score: 91.6 },
    },
    tier: "frontier",
    bestFor: ["research", "coding"],
    tradeoff: "Same capability class as Opus 5.5 but 25% more expensive — migrate.",
    sources: [{ label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" }],
    lastVerified: V,
    verification: "official",
    unverified: ["Release date inferred from the documented retirement commitment."],
  },
  {
    id: "claude-fable-5",
    apiId: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "anthropic",
    family: "Claude 5",
    series: { name: "Fable", rung: "flagship" },
    released: "2026-06-09",
    status: "legacy",
    servedBy: "Anthropic API",
    pricing: {
      input: 10,
      output: 50,
      cachedInput: 1,
      cacheWrite: 12.5,
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Same list price as Fable 5.1 but cache reads cost 4× more ($1 vs $0.25)."],
    },
    contextK: 1000,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "always", caching: "explicit", batch: true, fineTuning: false },
    deployment: ["Anthropic API", "AWS Bedrock", "Google Vertex AI", "Microsoft Foundry"],
    benchmarks: {
      "aa-index": { score: 50, note: "v4.3 (with fallback)" },
      lmarena: { score: 1506, note: "Sep 9 2026 snapshot" },
      "mmlu-pro": { score: 91.5 },
    },
    tier: "frontier",
    bestFor: ["research", "coding"],
    tradeoff: "Superseded by Fable 5.1 at identical token prices with cheaper caching.",
    sources: [{ label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" }],
    lastVerified: V,
    verification: "official",
    unverified: ["Release date inferred from retirement commitment; tracker SWE-bench Verified figures conflict (93.9–95.0) and are excluded."],
  },

  // ───────────────────────── OpenAI (official domain egress-blocked; indexed + trackers) ─────────────────────────
  {
    id: "gpt-6-astra",
    apiId: "gpt-6-astra",
    name: "GPT-6 Astra",
    provider: "openai",
    family: "GPT-6",
    series: { name: "Astra", rung: "flagship" },
    released: "2026-09-03",
    status: "ga",
    servedBy: "OpenAI API",
    pricing: {
      input: 10,
      output: 50,
      cachedInput: 1,
      cacheWrite: 12.5,
      cacheNote: "Automatic prefix caching; reads 0.1× input, writes 1.25× (GPT-5.6+ scheme); 30-minute reuse window.",
      batchDiscount: 0.5,
      longContext: { thresholdK: 272, input: 20, output: 75 },
      notes: ["Requests with >272K input tokens bill the whole request at 2× input / 1.5× output.", "Fast mode 2×; Batch and Flex 50%."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure", "AWS Bedrock"],
    benchmarks: {
      "aa-index": { score: 53, note: "v4.3 at max effort; tied with Claude Fable 5.1" },
      lmarena: { score: 1477, note: "Oct 2026 tracker snapshot" },
      gpqa: { score: 96.1, note: "AA independent run (OpenAI reports 96.0)" },
    },
    tier: "frontier",
    bestFor: ["research", "coding", "agents"],
    tradeoff: "OpenAI's flagship at the same list price as Claude Fable 5.1; long-context tier doubles input cost above 272K.",
    sources: [
      { label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" },
      { label: "Launch pricing coverage", url: "https://www.layer3labs.io/guides/gpt-6-astra-pricing" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/benchmarking-gpt-6-astra" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Official pricing page unreachable at verification; figures agree across ≥4 trackers.", "OpenAI reports DeepSWE v1.1 (74.8%) rather than SWE-bench Verified."],
  },
  {
    id: "gpt-6-1-sol",
    apiId: "gpt-6.1-sol",
    name: "GPT-6.1 Sol",
    provider: "openai",
    family: "GPT-6",
    series: { name: "Sol", rung: "mid" },
    released: "2026-09-29",
    status: "ga",
    servedBy: "OpenAI API",
    pricing: {
      input: 2,
      output: 10,
      cachedInput: 0.1,
      cacheWrite: 2.5,
      cacheNote: "Cache reads 0.05× input (95% off) — half GPT-6 Sol's cached rate.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Default model in Codex. Five reasoning-effort levels (none → max).", "Long-context multiplier above 272K likely applies as on GPT-6 Sol — unverified."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure"],
    benchmarks: {
      "aa-index": { score: 52, note: "v4.3 at max effort" },
    },
    tier: "balanced",
    bestFor: ["coding", "agents", "chat"],
    tradeoff: "Near-Astra agentic coding at one-fifth the price; the cheapest cached input of any mid-tier model.",
    sources: [
      { label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" },
      { label: "InfoQ DevDay 2026", url: "https://infoq.com/news/2026/10/openai-devday-2026" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/models/comparisons/gpt-6-1-sol-vs-gpt-6-luna" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Official page unreachable at verification; long-context tier for this model unconfirmed.", "OpenAI reports DeepSWE v1.1 (75.2%) rather than SWE-bench Verified."],
  },
  {
    id: "gpt-6-luna",
    apiId: "gpt-6-luna",
    name: "GPT-6 Luna",
    provider: "openai",
    family: "GPT-6",
    series: { name: "Luna", rung: "light" },
    released: "2026-09-22",
    status: "ga",
    servedBy: "OpenAI API",
    pricing: {
      input: 0.1,
      output: 0.5,
      cachedInput: 0.01,
      cacheWrite: 0.125,
      cacheNote: "Cache reads 0.1× input, writes 1.25×.",
      batchDiscount: 0.5,
      longContext: { thresholdK: 272, input: 0.2, output: 0.75 },
      notes: ["Successor to the nano tier at half GPT-5.6 Luna's price."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure"],
    benchmarks: {
      "aa-index": { score: 37, note: "v4.3 at max effort" },
    },
    tier: "economy",
    bestFor: ["bulk", "chat", "multimodal"],
    tradeoff: "Among the cheapest frontier-lab tokens available with a 1M window; capability ceiling well below Sol.",
    sources: [
      { label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/gpt-6-sol-and-luna-push-the-cost-efficiency-frontier" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Official page unreachable at verification."],
  },
  {
    id: "gpt-5-6-sol",
    apiId: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    provider: "openai",
    family: "GPT-5.6",
    series: { name: "Sol (5.6)", rung: "flagship" },
    released: "2026-07-09",
    status: "ga",
    servedBy: "OpenAI API",
    pricing: {
      input: 5,
      output: 30,
      cachedInput: 0.5,
      cacheWrite: 6.25,
      cacheNote: "Reads 0.1×, writes 1.25× (first generation with paid cache writes).",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Previous-generation flagship; GPT-6 Sol/6.1 Sol deliver comparable work at $2 / $10."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure"],
    benchmarks: {
      "aa-index": { score: 47, note: "v4.3 at max effort" },
      gpqa: { score: 94.1, note: "Tracker-harmonized" },
      "mmlu-pro": { score: 89.1 },
    },
    tier: "frontier",
    bestFor: ["research", "coding"],
    tradeoff: "Strong independent scores, but priced above GPT-6.1 Sol which OpenAI positions as a near-Astra replacement.",
    sources: [
      { label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" },
      { label: "benchlm AA mirror", url: "https://benchlm.ai/benchmarks/artificialanalysis" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Cached/cache-write prices derived from the published 0.1×/1.25× rule (read price independently confirmed).", "Fine-tuning availability unconfirmed."],
  },
  {
    id: "gpt-5-6-terra",
    apiId: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    provider: "openai",
    family: "GPT-5.6",
    series: { name: "Terra", rung: "mid" },
    released: "2026-07-09",
    status: "ga",
    servedBy: "OpenAI API",
    pricing: {
      input: 2,
      output: 12,
      cachedInput: 0.2,
      cacheWrite: 2.5,
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Cut from $2.50 / $15 on 2026-07-30. No GPT-6 Terra exists; GPT-6.1 Sol is the practical successor."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure"],
    benchmarks: {},
    tier: "balanced",
    bestFor: ["agents", "chat"],
    tradeoff: "Mid-tier of the previous generation; now outpriced on output by GPT-6.1 Sol.",
    sources: [
      { label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" },
      { label: "CloudZero GPT-5.6 pricing", url: "https://www.cloudzero.com/blog/gpt-5-6-pricing" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Cached prices derived from the 0.1×/1.25× rule.", "Context/max output confirmed for Sol-class; assumed identical for Terra.", "Earlier tracker index value (55) was not v4.3 — excluded."],
  },
  {
    id: "gpt-5-5",
    apiId: "gpt-5.5",
    name: "GPT-5.5",
    provider: "openai",
    family: "GPT-5.5",
    series: { name: "GPT-5.5", rung: "flagship" },
    released: "2026-04-24",
    status: "legacy",
    servedBy: "OpenAI API",
    pricing: {
      input: 5,
      output: 30,
      cachedInput: 0.5,
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Retired from ChatGPT and Codex apps on 2026-10-14; API unaffected."],
    },
    contextK: 1050,
    maxOutputK: 128,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: false },
    deployment: ["OpenAI API", "Microsoft Azure"],
    benchmarks: {
      lmarena: { score: 1481 },
      gpqa: { score: 93.5 },
      "swe-verified": { score: 82.6, selfReported: true, note: "OpenAI internal scaffold" },
      "mmlu-pro": { score: 88.1 },
    },
    tier: "frontier",
    bestFor: ["coding", "research"],
    tradeoff: "Well-benchmarked but two generations old at flagship prices.",
    sources: [{ label: "OpenAI pricing (official)", url: "https://platform.openai.com/docs/pricing" }],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Batch rate assumed 50% (standard); long-context tier unconfirmed."],
  },

  // ───────────────────────── Google (official domain egress-blocked; indexed + trackers) ─────────────────────────
  {
    id: "gemini-3-1-pro",
    apiId: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro",
    provider: "google",
    family: "Gemini 3",
    series: { name: "Pro", rung: "flagship" },
    released: "2026-02-19",
    status: "preview",
    servedBy: "Gemini API / Vertex AI",
    pricing: {
      input: 2.5,
      output: 15,
      cachedInput: 0.25,
      cacheNote: "Implicit + explicit caching; reads ~0.1× input plus storage ($/1M token-hours).",
      batchDiscount: 0.5,
      longContext: { thresholdK: 200, input: 4, output: 18 },
      notes: ["Raised from $2 / $12 on 2026-09-15.", "Thinking tokens billed as output. Still 'preview' after ~8 months; Gemini 3.5 Pro was cancelled."],
    },
    contextK: 1000,
    maxOutputK: 64,
    modalitiesIn: ["text", "image", "audio", "video", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "both", batch: true, fineTuning: false },
    deployment: ["Gemini API", "Google Vertex AI"],
    benchmarks: {
      lmarena: { score: 1486 },
      gpqa: { score: 94.1 },
      "swe-verified": { score: 80.6, note: "Leaderboard snapshot, Mar 2026" },
      aime: { score: 98.13 },
      "mmlu-pro": { score: 91.0 },
    },
    tier: "frontier",
    bestFor: ["research", "docs", "multimodal"],
    tradeoff: "Strongest native multimodality (audio/video in) and top math scores; preview status and a recent price rise.",
    sources: [
      { label: "Gemini API pricing (official)", url: "https://ai.google.dev/gemini-api/docs/pricing" },
      { label: "Artificial Analysis model page", url: "https://artificialanalysis.ai/models/gemini-3-1-pro-preview" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: [
      "Post-increase cached ($0.25) and >200K tier ($4 / $18) rates not confirmed on the official page.",
      "Max output (~64K) inferred from Google's Gemini 4 announcement.",
      "Not on AA Index v4.3 at snapshot (pre-v4.3 value excluded as non-comparable).",
    ],
  },
  {
    id: "gemini-3-8-flash",
    apiId: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    provider: "google",
    family: "Gemini 3",
    series: { name: "Flash", rung: "mid" },
    released: "2026-09-02",
    status: "ga",
    servedBy: "Gemini API / Vertex AI",
    pricing: {
      input: 0.75,
      output: 3.75,
      cachedInput: 0.075,
      cacheNote: "Introductory cached rate; storage fee likely $1 / 1M token-hours as on 3.5 Flash (unconfirmed).",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Introductory pricing through 2026-12-31; scheduled to double to $1.50 / $7.50 on 2027-01-01.", "Audio input priced the same as text."],
    },
    contextK: 1048,
    maxOutputK: 65,
    modalitiesIn: ["text", "image", "audio", "video", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "both", batch: true, fineTuning: false },
    deployment: ["Gemini API", "Google Vertex AI"],
    benchmarks: {
      "aa-index": { score: 41 },
      gpqa: { score: 94.4, selfReported: true, note: "Google model card" },
      "swe-verified": { score: 80.0, selfReported: true, note: "Google-reported" },
    },
    tier: "balanced",
    bestFor: ["chat", "multimodal", "agents", "docs"],
    tradeoff: "Best price-to-capability in Google's lineup today — but the intro price expires at year end.",
    sources: [
      { label: "Gemini 3.8 Flash model page (official)", url: "https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash" },
      { label: "Gemini API pricing (official)", url: "https://ai.google.dev/gemini-api/docs/pricing" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Cache storage fee for this model unconfirmed."],
  },
  {
    id: "gemini-3-5-flash",
    apiId: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "google",
    family: "Gemini 3",
    series: { name: "Flash", rung: "mid" },
    released: "2026-05-19",
    status: "ga",
    servedBy: "Gemini API / Vertex AI",
    pricing: {
      input: 1.5,
      output: 9,
      cachedInput: 0.15,
      cacheNote: "Cache storage $1.00 per 1M token-hours.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["Stable replacement for gemini-2.5-flash; no introductory discount — pricier than 3.8 Flash's intro rate."],
    },
    contextK: 1048,
    maxOutputK: 65,
    modalitiesIn: ["text", "image", "audio", "video", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "both", batch: true, fineTuning: false },
    deployment: ["Gemini API", "Google Vertex AI"],
    benchmarks: {
      "swe-verified": { score: 78.8, note: "Tracker-listed" },
    },
    tier: "balanced",
    bestFor: ["chat", "multimodal"],
    tradeoff: "Stable, no price cliff — but strictly more expensive than 3.8 Flash for the same tier.",
    sources: [{ label: "Gemini API pricing (official)", url: "https://ai.google.dev/gemini-api/docs/pricing" }],
    lastVerified: V,
    verification: "indexed",
  },
  {
    id: "gemini-3-5-flash-lite",
    apiId: "gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash-Lite",
    provider: "google",
    family: "Gemini 3",
    series: { name: "Flash-Lite", rung: "light" },
    released: "2026-07-21",
    status: "ga",
    servedBy: "Gemini API / Vertex AI",
    pricing: {
      input: 0.3,
      output: 2.5,
      cachedInput: 0.03,
      batchDiscount: 0.5,
      longContext: null,
      modalityNotes: ["Audio input $0.54 / 1M (Vertex global endpoint)."],
      notes: ["Google's recommended high-volume/subagent model and migration target off the 2.5 family."],
    },
    contextK: 1048,
    maxOutputK: 65,
    modalitiesIn: ["text", "image", "audio", "video", "pdf"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "both", batch: true, fineTuning: false },
    deployment: ["Gemini API", "Google Vertex AI"],
    benchmarks: {},
    tier: "economy",
    bestFor: ["bulk", "chat", "multimodal"],
    tradeoff: "Full multimodal input at economy prices; no independent benchmark coverage yet.",
    sources: [
      { label: "Vertex AI pricing (official)", url: "https://cloud.google.com/vertex-ai/generative-ai/pricing" },
      { label: "Gemini API pricing (official)", url: "https://ai.google.dev/gemini-api/docs/pricing" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Max output (~65K) from a single tracker.", "No independent benchmark scores at snapshot time."],
  },

  // ───────────────────────── DeepSeek (official docs via index) ─────────────────────────
  {
    id: "deepseek-v4-pro",
    apiId: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "deepseek",
    family: "DeepSeek V4",
    series: { name: "Pro", rung: "flagship" },
    released: "2026-08-13",
    status: "ga",
    servedBy: "DeepSeek API",
    license: "MIT (V4 open weights)",
    pricing: {
      input: 1.32,
      output: 3.96,
      cachedInput: 0.044,
      cacheNote: "Automatic disk prefix caching; cache hits ~1/30 of miss price.",
      batchDiscount: null,
      longContext: null,
      notes: ["Peak pricing shown (01:00–04:00 and 06:00–10:00 UTC weekdays). All other hours, including weekends, are 50% off: $0.66 / $1.98.", "Price schedule effective 2026-08-16."],
    },
    contextK: 1000,
    maxOutputK: 384,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: false, fineTuning: false },
    deployment: ["DeepSeek API", "Self-host (open weights)", "Third-party hosts"],
    benchmarks: {
      "aa-index": { score: 36, note: "V4 Pro 0813 at max effort" },
      gpqa: { score: 90.1, selfReported: true },
      "swe-verified": { score: 80.6, selfReported: true, note: "DeepSeek-reported" },
      "mmlu-pro": { score: 87.5, selfReported: true },
    },
    tier: "balanced",
    bestFor: ["coding", "bulk", "research"],
    tradeoff: "Open-weight flagship at a fraction of frontier prices; off-peak discount rewards batchable work, but no SLA-grade batch API.",
    sources: [
      { label: "DeepSeek pricing (official)", url: "https://api-docs.deepseek.com/quick_start/pricing" },
      { label: "V4-Pro GA note", url: "https://api-docs.deepseek.com/news/news260813" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Off-peak exact figures from official-domain extracts (medium confidence)."],
  },
  {
    id: "deepseek-flash",
    apiId: "deepseek-flash",
    name: "DeepSeek V4.1 Flash",
    provider: "deepseek",
    family: "DeepSeek V4",
    series: { name: "Flash", rung: "light" },
    released: "2026-09-10",
    status: "ga",
    servedBy: "DeepSeek API",
    pricing: {
      input: 0.3,
      output: 1.2,
      cachedInput: 0.006,
      cacheNote: "Automatic prefix caching; cache hits ~1/50 of miss price.",
      batchDiscount: null,
      longContext: null,
      notes: ["Peak pricing shown; off-peak (all hours outside 01:00–04:00 / 06:00–10:00 UTC weekdays) is 50% off: $0.15 / $0.60.", "Legacy ids deepseek-v4-flash resolve to this model."],
    },
    contextK: 1000,
    maxOutputK: 384,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: false, fineTuning: false },
    deployment: ["DeepSeek API", "Third-party hosts"],
    benchmarks: {},
    tier: "economy",
    bestFor: ["bulk", "chat", "coding"],
    tradeoff: "Extremely cheap cached input (0.6¢ / 1M); peak/off-peak schedule complicates budgeting.",
    sources: [
      { label: "DeepSeek pricing (official)", url: "https://api-docs.deepseek.com/quick_start/pricing" },
      { label: "V4.1-Flash note", url: "https://api-docs.deepseek.com/news/news260910" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Max output (384K) confirmed for V4 Pro only.", "Open-weight availability of V4.1-Flash not confirmed.", "No independent benchmark scores at snapshot time."],
  },

  // ───────────────────────── Alibaba Qwen ─────────────────────────
  {
    id: "qwen3-8-max",
    apiId: "qwen3.8-max",
    name: "Qwen3.8-Max",
    provider: "alibaba",
    family: "Qwen 3.8",
    series: { name: "Max", rung: "flagship" },
    released: "2026-08-03",
    status: "ga",
    servedBy: "Alibaba Cloud Model Studio (Singapore)",
    license: "Qwen3.8-Max License (custom; text-only checkpoint)",
    pricing: {
      input: 2,
      output: 6,
      cachedInput: null,
      batchDiscount: null,
      longContext: null,
      notes: ["Refreshed as qwen3.8-max-0902 at the same price.", "Open checkpoint (Qwen/Qwen3.8-2.4T-A95B) lacks the API version's 1M context and vision."],
    },
    contextK: 1000,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "none", batch: false, fineTuning: false },
    deployment: ["Alibaba Cloud Model Studio", "Self-host (restricted license)"],
    benchmarks: {
      "aa-index": { score: 45 },
    },
    tier: "frontier",
    bestFor: ["agents", "coding"],
    tradeoff: "Strong independent index for the price; regional pricing varies and cached-input pricing not published.",
    sources: [
      { label: "Model Studio pricing (official)", url: "https://www.alibabacloud.com/help/en/model-studio/model-pricing" },
      { label: "Qwen3.8 blog", url: "https://qwen.ai/blog?id=qwen3.8" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Max output not captured.", "Cached-input and batch pricing not published for this region."],
  },
  {
    id: "qwen3-5-plus",
    apiId: "qwen3.5-plus",
    name: "Qwen3.5-Plus (397B-A17B)",
    provider: "alibaba",
    family: "Qwen 3.5",
    series: { name: "Plus", rung: "mid" },
    released: "2026-02-15",
    status: "ga",
    servedBy: "Alibaba Cloud Model Studio (Singapore)",
    license: "Apache 2.0 (Qwen3.5-397B-A17B weights)",
    pricing: {
      input: 0.4,
      output: 2.4,
      cachedInput: null,
      cacheNote: "Context-cache discount offered; cached rate not captured.",
      batchDiscount: null,
      longContext: null,
      notes: ["Tiered by input length: $0.40–0.50 in / $2.40–3.00 out; lowest tier shown.", "Third-party reference: DeepInfra $0.54 / $3.40."],
    },
    contextK: 1000,
    maxOutputK: null,
    modalitiesIn: ["text", "image", "video"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "explicit", batch: false, fineTuning: false },
    deployment: ["Alibaba Cloud Model Studio", "Self-host (Apache 2.0)", "Third-party hosts"],
    benchmarks: {
      gpqa: { score: 88.4, selfReported: true, note: "Qwen model card" },
      "swe-verified": { score: 76.4, selfReported: true, note: "Qwen's own agent harness" },
      "mmlu-pro": { score: 87.8, selfReported: true, note: "Qwen model card" },
    },
    tier: "balanced",
    bestFor: ["multimodal", "chat", "bulk"],
    tradeoff: "Permissively licensed open flagship with native vision; benchmark coverage is thinner than the closed labs'.",
    sources: [
      { label: "Model Studio pricing (official)", url: "https://www.alibabacloud.com/help/en/model-studio/model-pricing" },
      { label: "Hugging Face weights", url: "https://huggingface.co/Qwen/Qwen3.5-397B-A17B-FP8" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Exact release day; cached-input rate; max output."],
  },

  // ───────────────────────── Meta Llama (no first-party API — third-party hosting) ─────────────────────────
  {
    id: "llama-4-maverick",
    apiId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    name: "Llama 4 Maverick",
    provider: "meta",
    family: "Llama 4",
    series: { name: "Maverick", rung: "flagship" },
    released: "2025-04-05",
    status: "ga",
    servedBy: "Together AI (third-party)",
    thirdPartyPricing: true,
    license: "Llama 4 Community License",
    pricing: {
      input: 0.27,
      output: 0.85,
      cachedInput: null,
      batchDiscount: null,
      longContext: null,
      notes: ["No first-party Meta API; price is Together AI serverless list. DeepInfra lists $0.15 / $0.60.", "Still Meta's current open-weight flagship — no newer open Llama as of Oct 2026."],
    },
    contextK: 1000,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "none", caching: "none", batch: false, fineTuning: true },
    deployment: ["Self-host", "Together AI", "DeepInfra", "AWS Bedrock", "Google Vertex AI"],
    benchmarks: {
      gpqa: { score: 69.8 },
      "mmlu-pro": { score: 80.5 },
    },
    tier: "economy",
    bestFor: ["bulk", "chat"],
    tradeoff: "Cheap, self-hostable and fine-tunable; a 2025 model without a reasoning mode, well behind current frontier scores.",
    sources: [
      { label: "Together AI pricing (third-party)", url: "https://www.together.ai/pricing" },
      { label: "Meta Llama 4 announcement", url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Host max-output limits vary; 1M context is host-dependent."],
  },

  // ───────────────────────── Mistral (official pricing via index) ─────────────────────────
  {
    id: "mistral-large-3",
    apiId: "mistral-large-3-2512",
    name: "Mistral Large 3",
    provider: "mistral",
    family: "Mistral 3",
    series: { name: "Large", rung: "flagship" },
    released: "2025-12-02",
    status: "ga",
    servedBy: "Mistral La Plateforme",
    license: "Apache 2.0",
    pricing: {
      input: 0.5,
      output: 1.5,
      cachedInput: null,
      cacheNote: "Cached input 'up to 90% off' per pricing page; per-model rate not published.",
      batchDiscount: 0.5,
      longContext: null,
      notes: ["675B MoE / 41B active, open weights."],
    },
    contextK: 256,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: true },
    deployment: ["Mistral API", "Self-host (Apache 2.0)", "Azure", "AWS Bedrock", "Google Vertex AI"],
    benchmarks: {
      "mmlu-pro": { score: 73.11, note: "Artificial Analysis independent run" },
    },
    tier: "balanced",
    bestFor: ["chat", "bulk", "docs"],
    tradeoff: "Very low list price and a permissive license; independent scores sit well below the frontier.",
    sources: [
      { label: "Mistral API pricing (official)", url: "https://mistral.ai/pricing/api/" },
      { label: "Model docs", url: "https://docs.mistral.ai/models/mistral-large-3-25-12" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Per-model cached-input rate; max output."],
  },
  {
    id: "mistral-medium-3-5",
    apiId: "mistral-medium-3-5-2604",
    name: "Mistral Medium 3.5",
    provider: "mistral",
    family: "Mistral 3",
    series: { name: "Medium", rung: "mid" },
    released: "2026-04-30",
    status: "ga",
    servedBy: "Mistral La Plateforme",
    license: "Modified MIT (weights on Hugging Face)",
    pricing: {
      input: 1.5,
      output: 7.5,
      cachedInput: null,
      batchDiscount: 0.5,
      longContext: null,
      notes: ["128B dense; replaced Devstral 2 and Magistral in Mistral's Vibe agent."],
    },
    contextK: 262,
    maxOutputK: 262,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: true },
    deployment: ["Mistral API", "Self-host", "Azure"],
    benchmarks: {
      gpqa: { score: 74.8, note: "Artificial Analysis independent run" },
      "mmlu-pro": { score: 76, note: "Artificial Analysis independent run" },
    },
    tier: "balanced",
    bestFor: ["coding", "agents"],
    tradeoff: "Mistral's current reasoning/coding workhorse with open weights; independent scores trail the closed frontier by a wide margin.",
    sources: [
      { label: "Mistral API pricing (official)", url: "https://mistral.ai/pricing/api/" },
      { label: "Model docs", url: "https://docs.mistral.ai/models/mistral-medium-3-5-26-04" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Pre-v4.3 AA index value (30.4) excluded as non-comparable."],
  },
  {
    id: "mistral-small-4",
    apiId: "mistral-small-2603",
    name: "Mistral Small 4",
    provider: "mistral",
    family: "Mistral 3",
    series: { name: "Small", rung: "light" },
    released: "2026-03-16",
    status: "ga",
    servedBy: "Mistral La Plateforme",
    license: "Open weights (license unconfirmed; Small line historically Apache 2.0)",
    pricing: {
      input: 0.15,
      output: 0.6,
      cachedInput: null,
      batchDiscount: 0.5,
      longContext: null,
    },
    contextK: 262,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: true, fineTuning: true },
    deployment: ["Mistral API", "Self-host"],
    benchmarks: {},
    tier: "economy",
    bestFor: ["bulk", "chat"],
    tradeoff: "Among the cheapest first-party tokens with a 262K window; capability unmeasured by the independent leaderboards used here.",
    sources: [{ label: "Mistral API pricing (official)", url: "https://mistral.ai/pricing/api/" }],
    lastVerified: V,
    verification: "indexed",
    unverified: ["License; max output; no independent benchmark scores."],
  },

  // ───────────────────────── xAI (official docs via index) ─────────────────────────
  {
    id: "grok-4-7",
    apiId: "grok-4.7",
    name: "Grok 4.7",
    provider: "xai",
    family: "Grok 4",
    series: { name: "Grok", rung: "flagship" },
    released: "2026-09-21",
    status: "ga",
    servedBy: "xAI API",
    pricing: {
      input: 2,
      output: 6,
      cachedInput: 0.5,
      batchDiscount: null,
      longContext: null,
      notes: ["'Grok 4.7 Fast' serving tier at 2× token rates.", "Same list price as Grok 4.6."],
    },
    contextK: 500,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: false, fineTuning: false },
    deployment: ["xAI API"],
    benchmarks: {
      "aa-index": { score: 46, note: "v4.3 at xhigh effort" },
    },
    tier: "frontier",
    bestFor: ["coding", "agents"],
    tradeoff: "Cheapest output price among closed-lab flagships; xAI reports DeepSWE/CursorBench rather than the classic benchmarks, and there is no batch tier.",
    sources: [
      { label: "xAI pricing (official)", url: "https://docs.x.ai/developers/pricing" },
      { label: "Grok 4.7 announcement", url: "https://x.ai/news/grok-4-7" },
      { label: "Artificial Analysis", url: "https://artificialanalysis.ai/articles/benchmarking-grok-4-7" },
    ],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Max output; long-context tier (4.6 had $4 / $12 above 200K — not confirmed for 4.7).", "GPQA / MMLU-Pro not yet published by independent trackers."],
  },
  {
    id: "grok-4-5",
    apiId: "grok-4.5",
    name: "Grok 4.5",
    provider: "xai",
    family: "Grok 4",
    series: { name: "Grok", rung: "flagship" },
    released: "2026-07-15",
    status: "ga",
    servedBy: "xAI API",
    pricing: {
      input: 2,
      output: 6,
      cachedInput: 0.3,
      batchDiscount: null,
      longContext: { thresholdK: 200, input: 4, output: 12 },
      notes: ["Requests above 200K context bill at $4 / $12."],
    },
    contextK: 500,
    maxOutputK: null,
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    features: { toolCalling: true, structuredOutput: true, reasoning: "optional", caching: "implicit", batch: false, fineTuning: false },
    deployment: ["xAI API"],
    benchmarks: {
      gpqa: { score: 93.1, note: "Artificial Analysis GPQA run" },
    },
    tier: "frontier",
    bestFor: ["coding", "agents"],
    tradeoff: "Still served at the same price as 4.7 with a published GPQA score; superseded as flagship.",
    sources: [{ label: "xAI pricing (official)", url: "https://docs.x.ai/developers/pricing" }],
    lastVerified: V,
    verification: "indexed",
    unverified: ["Exact release day.", "Earlier tracker AA index value (53.8) predates v4.3 — excluded."],
  },
];

/** Seeded pricing-change log (last ~3 months), newest first. The cron appends to it. */
export const SEED_NEWS: NewsItem[] = [
  {
    date: "2026-10-16",
    title: "Google retires the entire Gemini 2.5 generation",
    body: "Gemini 2.5 Pro, Flash and Flash-Lite shut down on October 16; Google's migration targets are Gemini 3.8 Flash and 3.5 Flash-Lite. New projects already receive 'no longer available'.",
    provider: "google",
    kind: "deprecation",
    source: { label: "Gemini API deprecations", url: "https://ai.google.dev/gemini-api/docs/deprecations" },
  },
  {
    date: "2026-10-14",
    title: "GPT-5.5 retired from ChatGPT and Codex apps (API unaffected)",
    body: "OpenAI removed GPT-5.5 from its consumer and Codex surfaces; the API keeps serving it at $5 / $30.",
    provider: "openai",
    kind: "deprecation",
    source: { label: "Coverage", url: "https://orcarouter.ai/blog/gpt-5-5-remains-available-openai-api-codex-api-key" },
  },
  {
    date: "2026-09-30",
    title: "Anthropic deprecates Claude Sonnet 4.5 — retirement 2026-11-30",
    body: "Replacement is Claude Sonnet 5.5 at $2 / $10, a net cut from Sonnet 4.5's $3 / $15.",
    provider: "anthropic",
    kind: "deprecation",
    source: { label: "Model deprecations", url: "https://platform.claude.com/docs/en/about-claude/model-deprecations" },
  },
  {
    date: "2026-09-30",
    title: "Gemini 4 'Argon' announced at $2 / $10 introductory (not generally available); Gemini 3.5 Pro cancelled",
    body: "Google confirmed Gemini 3.5 Pro will not ship and announced Gemini 4 Argon for its Fairwind program and US government, with pricing rising to $4 / $20 after the intro period and a 1M-token output limit.",
    provider: "google",
    kind: "new-model",
    source: { label: "Coverage", url: "https://www.thestack.technology/google-finally-eases-open-the-lid-on-gemini-4-argon/" },
  },
  {
    date: "2026-09-29",
    title: "GPT-6.1 Sol launches at $2 / $10 with cached input cut to $0.10",
    body: "Announced at DevDay 2026. Same token prices as GPT-6 Sol with cached input halved (95% below standard input). Becomes the Codex default.",
    provider: "openai",
    kind: "price-cut",
    source: { label: "InfoQ", url: "https://infoq.com/news/2026/10/openai-devday-2026" },
  },
  {
    date: "2026-09-28",
    title: "Claude Sonnet 5.5 launches at $2 / $10 (price-neutral vs Sonnet 5)",
    body: "Cache reads $0.20, batch 50% off. Anthropic now reports SWE-bench Pro (81.3%) rather than Verified for this model.",
    provider: "anthropic",
    kind: "new-model",
    source: { label: "Sonnet 5.5 overview", url: "https://platform.claude.com/docs/en/models/sonnet-5-5/overview" },
  },
  {
    date: "2026-09-22",
    title: "Claude Opus 5.5 launches at $4 / $20 — 20% below Opus 5",
    body: "Cache reads $0.20 (0.05×), cache writes $5, fast mode $8 / $40 (down from $10 / $50 on Opus 5). Anthropic's new recommended default.",
    provider: "anthropic",
    kind: "price-cut",
    source: { label: "Opus 5.5 overview", url: "https://platform.claude.com/docs/en/models/opus-5-5/overview" },
  },
  {
    date: "2026-09-22",
    title: "GPT-6 Sol ($2 / $10) and GPT-6 Luna ($0.10 / $0.50) halve prior-generation prices",
    body: "Sol replaces GPT-5.6 Sol's $4 / $20 tier at half price; Luna halves GPT-5.6 Luna ($0.20 / $1.20). Both carry the >272K long-context multiplier (2× input, 1.5× output).",
    provider: "openai",
    kind: "price-cut",
    source: { label: "CloudZero", url: "https://www.cloudzero.com/blog/gpt-6-pricing/" },
  },
  {
    date: "2026-09-21",
    title: "xAI releases Grok 4.7 at unchanged $2 / $6",
    body: "Replaces Grok 4.6 as flagship; cached input $0.50; a 'Fast' serving tier at 2× rates.",
    provider: "xai",
    kind: "new-model",
    source: { label: "xAI", url: "https://x.ai/news/grok-4-7" },
  },
  {
    date: "2026-09-15",
    title: "Gemini 3.1 Pro price increase: $2 / $12 → $2.50 / $15",
    body: "A 25% rise on both input and output for the ≤200K tier. Whether the >200K tier ($4 / $18 at launch) changed is unconfirmed.",
    provider: "google",
    kind: "price-increase",
    source: { label: "Gemini API pricing", url: "https://ai.google.dev/gemini-api/docs/pricing" },
  },
  {
    date: "2026-09-10",
    title: "DeepSeek V4.1 Flash replaces V4 Flash at the same price point",
    body: "deepseek-flash now serves V4.1-Flash: $0.30 / $1.20 peak, half that off-peak, cache hits $0.006.",
    provider: "deepseek",
    kind: "new-model",
    source: { label: "DeepSeek news", url: "https://api-docs.deepseek.com/news/news260910" },
  },
  {
    date: "2026-09-03",
    title: "GPT-6 Astra launches at $10 / $50",
    body: "Cached input $1, cache writes $12.50, batch/flex 50%, fast mode 2×. Requests above 272K input tokens bill at 2× input and 1.5× output.",
    provider: "openai",
    kind: "new-model",
    source: { label: "Launch pricing coverage", url: "https://www.layer3labs.io/guides/gpt-6-astra-pricing" },
  },
  {
    date: "2026-09-02",
    title: "Gemini 3.8 Flash GA at $0.75 / $3.75 introductory pricing (doubles on 2027-01-01)",
    body: "Third Flash release in six weeks (3.6 → 3.7 → 3.8). Intro pricing runs through 2026-12-31, then $1.50 / $7.50 with cached input $0.15.",
    provider: "google",
    kind: "new-model",
    source: { label: "Gemini 3.8 Flash model page", url: "https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash" },
  },
  {
    date: "2026-09-01",
    title: "Claude Fable 5.1 launches at $10 / $50 with cache reads cut 75% to $0.25",
    body: "Same token prices as Fable 5; cache-read multiplier drops from 0.1× to 0.025×.",
    provider: "anthropic",
    kind: "price-cut",
    source: { label: "Fable 5.1 overview", url: "https://platform.claude.com/docs/en/models/fable-5-1/overview" },
  },
  {
    date: "2026-08-28",
    title: "Anthropic makes Claude Sonnet 5's $2 / $10 permanent",
    body: "The scheduled 2026-09-01 increase to $3 / $15 will not occur (pricing page footnote). Exact announcement date unconfirmed.",
    provider: "anthropic",
    kind: "pricing-change",
    source: { label: "Anthropic pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing" },
  },
  {
    date: "2026-08-16",
    title: "DeepSeek V4 Pro moves to peak / off-peak pricing",
    body: "Peak $1.32 / $3.96 (01:00–04:00 and 06:00–10:00 UTC weekdays); all other hours 50% off at $0.66 / $1.98. Replaces the lower preview-period prices.",
    provider: "deepseek",
    kind: "pricing-change",
    source: { label: "DeepSeek pricing", url: "https://api-docs.deepseek.com/quick_start/pricing" },
  },
  {
    date: "2026-08-03",
    title: "Alibaba ships Qwen3.8-Max at $2 / $6",
    body: "Alibaba's new overall flagship on Model Studio; weights later posted under a custom license. Refreshed as qwen3.8-max-0902 on September 2 at the same price.",
    provider: "alibaba",
    kind: "new-model",
    source: { label: "Qwen blog", url: "https://qwen.ai/blog?id=qwen3.8" },
  },
  {
    date: "2026-07-30",
    title: "GPT-5.6 Terra price cut: $2.50 / $15 → $2 / $12",
    body: "Three weeks after the GPT-5.6 family GA.",
    provider: "openai",
    kind: "price-cut",
    source: { label: "CloudZero", url: "https://www.cloudzero.com/blog/gpt-5-6-pricing" },
  },
  {
    date: "2026-07-24",
    title: "DeepSeek retires deepseek-chat / deepseek-reasoner (V3.2)",
    body: "End of the V3.x price list ($0.28 / $0.42). Reasoning is now a mode switch on the V4 models.",
    provider: "deepseek",
    kind: "deprecation",
    source: { label: "DeepSeek updates", url: "https://api-docs.deepseek.com/updates/" },
  },
  {
    date: "2026-07-21",
    title: "Gemini 3.6 Flash and 3.5 Flash-Lite GA; Flash intro pricing introduced",
    body: "Flash intro rate $0.75 / $3.75 (half of list); Flash-Lite at $0.30 / $2.50.",
    provider: "google",
    kind: "new-model",
    source: { label: "Coverage", url: "https://www.datacamp.com/blog/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber" },
  },
];
